### ISSUE TITLE
Issue with slideshow at 500ms

### ISSUE THREAD

**Issue by Hira11220** [avluis/Hentoid#1000]
**Hentoid Version**:1.16.6a

**Device/Android Version**:fails on Samsung Tab S7/SM-T875 12

**Issue details / Repro steps**:instead of running each picture in the delay of 500ms, it run the whole book so fast that the pictures do not have enough time to load

https://user-images.githubusercontent.com/109822674/180504862-9b752523-c447-4470-85fc-5e8967027a3f.mp4

**Stack trace / LogCat**:there are no error message in the log
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for the video. The issue has been fixed and will be made available on next release
