### ISSUE TITLE
Please allow redownload from scratch on finished book

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1004]
My entire book got deleted after i press "allow deleting external content" i missed that word i thought on external Library i can't delete files on external but it deletes entire book please remove that feature or gives more accurate word.

I lost 1200++ book coz of that everything i collect just gone everything are lost forever. Please remove that shit deleting library book ppl will always mistaken that

**Comment by RobbWatershed** [comment]
Thanks for your feedback. However, there are a few things to improve so we can start processing it :

1/ What's the relationship between the title and the description of your issue ? They seem unrelated

2/ The "allow deleting external content" setting just does what it says : it unlocks the delete action in the library screen. That setting doesn't delete anything when enabled. I think you forgot to tell us all the steps you took. Could you please be more precise / add a step-by-step walkthrough and/or screenshots ?

Thanks in advance~

**Comment by Chocolalolz** [comment]
>my SD card are full
>I tried external library to download
>I thought the downloader can be movs into internal storage
>It stills download into my SD card causing error
>Change main storage into internal phone
>Existing library moved on external library
>Press allowing delete library
>Didn't know it will delete my external library
>Ended losing everything
>Now i download the book 1 by 

Advice :
-Use warning pop up on "Allowing deleting on external content. Example : Warning u will lost all your data on external library press yes to proceed

-Allow redownload book from scratch or missing part on book (Of there's select all or selected book much better).


Sometimes i got issues while book finished downlading it stills on library instead on Error Library
![Uploading Screenshot_2022-08-11-22-26-54-009_me.devsaki.hentoid.jpg…]()

**Comment by RobbWatershed** [comment]
I appreciate the effort, but I have to say your report is very confusing. I have not the slightest idea of what you did 1/ with Hentoid, 2/ with your file manager and 3/ with the Android app settings.

Last but not least, I'm not sure you have the correct understanding of what the external library feature is. We've created a new page dedicated to that : https://github.com/avluis/Hentoid/wiki/Using-the-external-library


Onto the extra info :

> Use warning pop up on "Allowing deleting on external content. Example : Warning u will lost all your data on external library press yes to proceed

Once again, **unchecking that setting does not have any effect on your files** !  You may review the code if you fancy. If I had to take a wild guess, I'd suspect one the many steps you previously took.

> Allow redownload book from scratch or missing part on book (Of there's select all or selected book much better).

I don't understand that part. That feature is already there. And it does not work for non-Hentoid external books, as the app has no clue about where the book has been downloaded from.

> Sometimes i got issues while book finished downlading it stills on library instead on Error Library

That's probably a display issue. Is it solved when restarting the app ?

**Comment by Chocolalolz** [comment]
>That's probably a display issue. Is it solved when restarting the app ?
I did restart the App but it didnt work

>I don't understand that part. That feature is already there. And it does not work for non-Hentoid external books, as the app has no clue about where the book has been downloaded from.
I think it's bug on a few phone there's a few book can't be redownloaded from scratch but if it's already on library and u press "Download from scratch" purging book willl stuck and nothing happends

**Comment by RobbWatershed** [comment]
Is there anything left to do here ?
