### ISSUE TITLE
Importing of books from exported file keeps failing download

### ISSUE THREAD

**Issue by N1c01337** [avluis/Hentoid#1007]
So I wanted to shift my books to my new SD card from my phone memory. I used the app export feature and then deleted my library. Having changed my download location' I tried importing from the json file I exported, it resulted in 299 download errors. I then pressed the redownload all but only 2 books could be successfully downloaded. When ever I tried pressing the redownload button for each book they would instantly get thrown back to the error pile.

Here is one of the error logs. 
Error log : begin
Hentoid ver: 1.16.8 (565)
API: 31
Device: SM-G985F
Start : 2022-08-24T16:03:12.395Z
End : 2022-08-24T16:03:12.395Z (00:00)
-----
Error log for Saimin Hitozuma OL-san [352372@nhentai] : 1 errors
2022-08-25T00:03:12.395 Image list - [Parsing]: No images have been found. Error = null @ /352372/
Error log : end

Is there a way to fix this or do I have to delete each queue and redownload them again.

**Comment by RobbWatershed** [comment]
Could have been many things. Maybe you need a VPN to access nhentai and forgot to turn it on, or the book has been removed from NH.

The export feature is _not_ meant for transferring books. You'd better bring the images along - see https://github.com/avluis/Hentoid/wiki/FAQ#Lib-4

**Comment by RobbWatershed** [comment]
No feedback from the OP => Closed
