### ISSUE TITLE
Can't open the link in the app

### ISSUE THREAD

**Issue by johnmohand** [avluis/Hentoid#1011]
Dear, sir 
I have a problem when I open a link with this app the program doesn't open this site, knowing that this link is one of the sites supported by this application. Please solve this problem. Thank you ❤️

**Comment by RobbWatershed** [comment]
...which site ? Could you provide a link that doesn't work ?

**Comment by johnmohand** [comment]
no it is not provide like  ,the site like E hentai ,n hentai ,luscious

**Comment by RobbWatershed** [comment]
I'm sorry but describing the issue in such general terms won't allow me to fix it.

=> Could you describe **precisely** and **step by step** how to reproduce your problem - or even better, post a video

Thanks in advance

**Comment by RobbWatershed** [comment]
No answer from the OP => Closed
