### ISSUE TITLE
Search bar history is blocking my keyboard

### ISSUE THREAD

**Issue by mish20011** [avluis/Hentoid#1013]
Just as the title says, I don't know how this works but its been blocking what I type

![Screenshot_20220913-214403](https://user-images.githubusercontent.com/72195360/189917951-60447192-965a-4226-abf4-f9eb1ebdc8e5.jpg)

**Hentoid Version**: 1.16.9

**Device/Android Version**: LG M700SDK Android 8.1

**Issue details / Repro steps**: Piling up search history results to an overlay of the search suggestion history instead of behind, when it shouldn't but I never know since this was implemented like this when it came it.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

https://streamable.com/490zq3

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
We're fully aware about that and are waiting for a 3rd party library to be updated. See https://github.com/skydoves/PowerMenu/issues/90 for the whole story.

PS : glad you found your way to GitHub @mish20011 !

**Comment by mish20011** [comment]
> We're fully aware about that and are waiting for a 3rd party library to be updated. See [skydoves/PowerMenu#90](https://github.com/skydoves/PowerMenu/issues/90) for the whole story.
> 
> PS : glad you found your way to GitHub @mish20011 !

Yes, I actually have this account for 2 years now but just never bothered using github

**Comment by RobbWatershed** [comment]
PowerMenu has just been updated, and we integrated the new version into Hentoid.

The fix will be available on next release.

**Comment by RobbWatershed** [comment]
Fixed in v1.16.11
