### ISSUE TITLE
Searching when you have groups gets you stuck in the groups screen

### ISSUE THREAD

**Issue by DRWAUN** [avluis/Hentoid#1014]
**Hentoid Version**: 1.16.8

**Device/Android Version**: Android 10

**Issue details / Repro steps**:

1. Have more than 1 group
2. Go to a group 
3. Search in that group
4. Seen: app returns to group overview and trying to click any of the groups results in the search bar popping up again and the app reloading group overview again. This happens with each press on a group. Only sometimes does it open the pressed group (haven't figured out in what scenario). You can't access any of the groups until you restart the app.  

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
No error message

[search + groups.zip](https://github.com/avluis/Hentoid/files/9592511/search.%2B.groups.zip)
(video zipped because it was larger than 10MB)
@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Published in today's v1.16.11
