### ISSUE TITLE
can't download in hentai2read

### ISSUE THREAD

**Issue by mish20011** [avluis/Hentoid#1018]
Content can't be downloaded, downloading circle keeps on going

**Hentoid Version**: 
1.16.9

**Device/Android Version**:
LG Q6 M700

**Issue details / Repro steps**:
Other sites can download normally except for hentai2read, tried clearing app data, still the same

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

![Capture+_2022-10-05-23-37-52](https://user-images.githubusercontent.com/72195360/194102701-469e0f25-1e17-4d48-a11c-256c2b2aba1a.png)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for your feedback. That issue is known and the fix will be made available around monday.

**Comment by RobbWatershed** [comment]
Released on today's v1.16.10
