### ISSUE TITLE
Can't login on e-hentai/exhentai

### ISSUE THREAD

**Issue by asd3df5** [avluis/Hentoid#1019]
**Hentoid Version**: 1.16.9

**Device/Android Version**: OnePlus 8 (5G) T-Mobile / Android 12 (default Oxygen OS) 

**Issue details / Repro steps**:

So I want to be able to use my settings when I browse e-hentai.org/exhentai. In order to do so, I need to log into my profile when I'm using the app. 

I click "MyHome" at the top of the page and I'm taken to a log in page. Regardless of what I put into the username/password it will bring me to another page and that page will say "The captcha was not entered correctly. Please try again." I enter the correct login credentials, click the captcha checkmark, then press "log me in." I'm told "username or password incorrect." The username and/or password aren't incorrect as they work on other platforms (e.g. desktop browsers). 

I will note a few things:

1. Underneath the Captcha it states "IF YOU DO NOT SEE THE CAPTCHA, ENABLE JAVASCRIPT AND DISABLE YOUR ADBLOCKER"

2. If I enter my login credentials before clicking on the captcha, the captcha image puzzle will never trigger. Instead I'll just see the checkmark without any sort of puzzle to solve. If I click the captcha before entering my credentials, roughly 50% of the time the image puzzle will trigger.

3. I've tried using both the augmented and vanilla browsers.

**Comment by RobbWatershed** [comment]
Thanks for the detailed report. I didn't know they added a captcha on these sites 🤦‍♂️ 

If there's a potential adblock issue, you should definitely disable augmented browser to log in.

If you have enabled DNS over HTTPS, you should also disable that to log in.

**Comment by RobbWatershed** [comment]
The login page to use is not "my home", but "forums". The app brings you there when using the exHentai source.

**Comment by RobbWatershed** [comment]
> The top of the page says "Welcome to the E-hentai Community Forums" and the theme is grey/silver and white.

That's the one :-)

> I get the error message "Username or password incorrect."

Does that even work on a normal browser ? If you see that message, it has nothing to do with Hentoid.

I tried on my end and never saw any captcha... maybe try from a different zone, using a VPN ?

**Comment by RobbWatershed** [comment]
No news from the OP => Closed
