### ISSUE TITLE
Kemono.party source

### ISSUE THREAD

**Issue by Kimphunh** [avluis/Hentoid#1020]
Kemono is a public archiver for:

Patreon
Pixiv Fanbox
Gumroad
SubscribeStar
DLsite
Discord
Fantia
Boosty
Afdia

Kemono is currently having 39662 artists

**Comment by RobbWatershed** [comment]
Th team has been talking about your suggestion today. Two issues have been underlined :

1/ Hentoid can only download images directly hosted on Kemono. Images linked from Kemono to a 3rd party host (e.g. dropbox or mega, as in many Kemono posts) _will not_ be supported

2/ We observed that most content Kemono is hosting is also available _and tagged_ on e-hentai and exHentai, which are already supported by the app. There's questionable added value in supporting a source that has little exclusive content, and no tags.

3/ Hentoid does not, and will not support downloading or reading videos

Considering that, are you still interested in promoting Kemono support ?  If so, what added value would it bring ?

Thanks in advance for your quick feedback. We're holding a community voting very soon on Discord.
