### ISSUE TITLE
Can you make log errors readable? Cos From 1933 folder on my tablet, only 1800detected. And make folder with no json file in errors queue. To make user can download from scratch again .

### ISSUE THREAD

**Issue by Kiki88x** [avluis/Hentoid#1022]
**Hentoid Version**: 1. 16. 11

**Device/Android Version**: sony tab z4

**Issue details / Repro steps**: first my hentoid always crashes and in reinstall it, when i try to import from my previous folder only 1800 detected the another one is errors/ steps : 1. Open hentoid folder, 2. Automatically scan the folder, 3. Some documents error, 4. I look at the log, but its hard to read which folder that have an error. 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
``` import book KO! (No json found) 

<!-- Bonus points if you attach a relevant screenshot or a screen recording -->

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Hi there,


Thanks for your feedback.

> Can you make log errors readable

Error logs _are_ readable - they're text files written in english. Could you elaborate ?

> I look at the log, but its hard to read which folder that have an error.

Look for lines that have the word "KO" - they are usually located at the beginning of the file

> Make folder with no json file in errors queue

If there's no JSON, the app has no idea what kind of book it is and where it comes from. As a consequence, it can't add it to the queue.

> first my hentoid always crashes

Could you go to Tools > App logs and copy/paste the log called "latest_crash" ?

**Comment by RobbWatershed** [comment]
No feedback from the OP => Closed
