### ISSUE TITLE
How to disable search history 

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1023]
Guys i just searching on option idk how to disable search history on books that i download can anyone help me?

**Comment by RobbWatershed** [comment]
On which screen ?

**Comment by Chocolalolz** [comment]
At the start of the page on Library book

**Comment by RobbWatershed** [comment]
That one ? https://user-images.githubusercontent.com/72195360/189917951-60447192-965a-4226-abf4-f9eb1ebdc8e5.jpg

**Comment by Chocolalolz** [comment]
Ah yes that one sry I'm busy lately for late reply

**Comment by RobbWatershed** [comment]
You can't disable it for now, just clear it. Disabling will be a feature in a future update.
