### ISSUE TITLE
Hitomi Gallery not opening for certain books

### ISSUE THREAD

**Issue by neeth-kun** [avluis/Hentoid#1025]
**Hentoid Version**: 1.17.0

**Device/Android Version**: Pixel 6, Android 13

**Issue details / Repro steps**: I tried to open galleries for some books on HITOMI, but the browser crashes and redirects to the home screen of the app. After repetition with mentioned books, it happens for books that have many pages. To be clear, the app is not crashing. Only the Hitomi browser is crashing for certain books.

**Stack trace / LogCat**:
My App Logs tab is empty and I could not find logs elsewhere.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for your feedback. Does it still happen with the latest version ? Can you share an URL to a book that crashes ?
