### ISSUE TITLE
Export gallery not responding 

### ISSUE THREAD

**Issue by Kiki88x** [avluis/Hentoid#1027]
**Hentoid Version**: v1.17.1(600)

**Device/Android Version**: sony experia xz1, oreo

**Issue details / Repro steps**:  as usually when we want to export gallery to json, i go to setting, import/export gallery. Then when i want to export my gallery to json, app always not responding, before update i still can do export my gallery into json. 

**Stack trace / LogCat**: app not responding, close app. And always restarting the app. 
```ruby
paste stack trace and/or log here
```

![Screenshot_20221224-004608](https://user-images.githubusercontent.com/70476061/209362503-9344a38a-3882-4269-ac3a-0e3099870619.png)

And i want to request please add (koushoku.Org) because i can't download any doujin in tachiyomi app. Please... Please... 🙏🙏

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Fixed on today's v1.17.2. Thanks for your report !
