### ISSUE TITLE
Refresh button on Shuffle 

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1028]
Hey i have an idea about this one.

Can u guys makes the reshuffle button looks like refresh button? I mean it just will only works on "Reshuffle settings"

There's 2 idea that comes in my mind

1. Adds refresh button to shuffle entire library like pulling down at the top library looks like u wanted refresh some pages.

2. Since i have so many books i need to shuffle my library there's button "go to top page" at the bottom right screen. The idea while u'r already on the top of library just change the button into shuffle option

I appreciate ur works guys and those setting makes only for "Reshuffle settings" if not it will be messed up

**Comment by RobbWatershed** [comment]
Hi again :) And thanks for your feedback !

First things first, we need to clarify a couple things to ensure we're talking about the same concepts :

1/ Are you talking about the reshuffle button that appears when random sorting is on ?

2/ What's the difference between what you describe and the current "random sorting" ? Do you want a "shortcut" that allows you to shuffle your collection in one single tap ?

**Comment by Chocolalolz** [comment]
1. Well yes it's actually same as shuffle button
2. Well this app used to be use by one hand right? From my experience it's really bad struggle to change and press settings again and again 


Explanation:
1. See the button on bottom right? U can change it into reshuffle button but only when u are the top page
![IMG_20230118_013112](https://user-images.githubusercontent.com/37593430/212983039-609d67c7-44b1-438f-961a-d26e3005e0fc.jpg)

2. See? As u reach the top of page the button will gone so instead there's nothing on it it will be easy adding button there (Atleast u can adjust the button freely like moving anywhere) but if u can't just put it on bottom
![IMG_20230118_013306](https://user-images.githubusercontent.com/37593430/212983381-17279c89-9d26-4d58-a47f-1f1c8e1b5170.jpg)

3. Well adjusting reshuffle button that can move freely are hard to do it right? I have another solution make it u can reshuffle the library at the top page like this video

https://user-images.githubusercontent.com/37593430/212983866-099936ef-a96e-40d1-a8ae-e171c36ce24e.mp4

Note : Reshuffle button only appear on top page as long u scroll the button will be normally change into "Pin to top" button again. One more thing just add those options on "Reshuffle Mode" only it will be messed up if u adding on normal

**Comment by RobbWatershed** [comment]
Gotcha. Thanks for your input!

**Comment by RobbWatershed** [comment]
Implemented shuffle upon swiping, like in the video you posted. Reusing the "go to top" button looked messy to me.
