### ISSUE TITLE
Gallery view for merged books

### ISSUE THREAD

**Issue by Padpoy** [avluis/Hentoid#1029]
Only the list view is boring, want a Gallery view of the cover of the merged books

**Comment by RobbWatershed** [comment]
Not sure about making a grid view, as the order of the books won't be as easy to manage.
However, the additon of the cover to the current list view is a nice idea.

**Comment by RobbWatershed** [comment]
Changes for next release :
- Merge books dialog displays book covers
- Split books dialog displays chapter covers
- Foldable chapters view in gallery screen displays chapters covers
