### ISSUE TITLE
[feature request] Merged books should be relocated to the top of the library when sorted by download date 

### ISSUE THREAD

**Issue by mish20011** [avluis/Hentoid#1030]
**Hentoid Version**: 1.17.2

**Device/Android Version**: LG K430

**Issue details / Repro steps**: its not actually an error, more like a feature request, instead of having the merged books be at the bottom, it should be considered a new download so its in the uppermost of the sorted library and not at the bottom

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for your feedback. Can you confirm you're sorting by "Download date (completed)" and not "Download date (processed)"

**Comment by mish20011** [comment]
> Thanks for your feedback. Can you confirm you're sorting by "Download date (completed)" and not "Download date (processed)"

![Screenshot_20230112-233432](https://user-images.githubusercontent.com/72195360/212110845-4ad04d10-44ee-4fa4-9d2e-1791ab6312a7.jpg)
downloaded 4 chapters of this and its at the very top
![Screenshot_20230112-233549](https://user-images.githubusercontent.com/72195360/212110999-d91ccfa8-d04b-4e80-8167-8848123a4855.jpg)
after merging it went to the very bottom just like my other merged books

**Comment by RobbWatershed** [comment]
Fixed on today's v1.17.3
