### ISSUE TITLE
#Ask

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1052]
![IMG_20230219_085408](https://user-images.githubusercontent.com/37593430/219939828-61c52bac-9518-49ae-8ead-9dc56aa8f089.jpg)

Hi after new update it's kinda annoy me when searching the download button bar appear can u tell me how to remove this button?

**Comment by RobbWatershed** [comment]
You can't. That's part of the updated UI layout.

**Comment by Chocolalolz** [comment]
Ah this is annoying this feature can't let me use one hand mode freely anymore since it blocks "next page" button pn Nhentai

**Comment by RobbWatershed** [comment]
On nhentai, the ">" button is not the only way to go to the next page. You can click the image itself to go to the next page.
