### ISSUE TITLE
nhentai download/stream

### ISSUE THREAD

**Issue by omega7pro** [avluis/Hentoid#1054]
**Hentoid Version**: 1.17.6 (638)

**Device/Android Version**:SAMSUNG Galaxy Tab A

**Issue details / Repro steps**:The download/stream button doesn't show up on anything for nhentai and long press doesn't work either. Tried it on IMHentai, HentaiFox, and 8Muses, and they work as intended. It only seems to not work on nhentai. (Note that I don't use the other sites, and I have tried whilst not logged in.)

**Stack trace / LogCat**:No error message

**Comment by RobbWatershed** [comment]
Works fine here. You may try a combination of the following to fix your issue :
- Clear app cache
- Clear browser cache
- Disable or enable "augmented browser"
- Disable or enable DNS over HTTPS
- Check the settings of your VPN or DNS app, if you have any

**Comment by omega7pro** [comment]
The DNS over HTTPS thing seems to have worked, but its definitely finicky on my end.
