### ISSUE TITLE
Bug Blank field

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1058]
![Screenshot_20230331-194301](https://user-images.githubusercontent.com/37593430/229123544-30a4e55a-40be-4d76-909e-e03a89ff6077.jpg)

Help there's a bug on the app I don't have any Queue download but it keeps appear I can't delete or do something about this

Device: Infinix note 11
Hentoid Ver : 1.17.7

**Comment by RobbWatershed** [comment]
You can remove it by using **top right menu > Cancel all**

I'm still not sure how to reproduce that issue, though
