### ISSUE TITLE
Feature Request: Release on F-Droid

### ISSUE THREAD

**Issue by marek22k** [avluis/Hentoid#1063]
Hello,

since the app is FLOSS, it would be nice if this would be published in F-Droid.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
The app is not FLOSS as it features :
- Firebase
- ObjectBox (apparently not FLOSS : https://github.com/objectbox/objectbox-java/issues/1102)

Sorry~

**Comment by marek22k** [comment]
Thanks for the answer!
