### ISSUE TITLE
[API27] Can't download gallery using long press

### ISSUE THREAD

**Issue by mish20011** [avluis/Hentoid#1065]
**Hentoid Version**: 1.17.10

**Device/Android Version**: LG Q6

**Issue details / Repro steps**: when quick download is enabled, you should be able to long press a gallery to quickly add it to download queue right? But for sme reason its not reacting at all when I long press it, What it does is showing a popup link when pressing it but doesn't do anything, tried changing the threshold, download action but still the same (it did work for some after repeated long presses, but in others it does not). I use ehentai, hentaifox, and hentai2read mainly, it sometimes work in hentaifox, in ehentai I can't even long press the gallery links in the comments anymore to download coz it doesn't queue, in hentai2read it straight up does not work, idk what happened but it didn't used to be like this 😐

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

![Screenshot_2023-06-11-12-48-49](https://github.com/avluis/Hentoid/assets/72195360/3852c953-c7ec-41d4-8338-7299468b339a)
![Screenshot_2023-06-11-12-48-21](https://github.com/avluis/Hentoid/assets/72195360/61062752-f594-4a8a-a5f5-2ccb0302f8c8)
![Screenshot_2023-06-11-12-42-13](https://github.com/avluis/Hentoid/assets/72195360/4c17b107-ae87-4a6b-9105-975a119a80ae)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Heya! Could you tell us which Android version you're using ?
Thanks~

**Comment by mish20011** [comment]
> Heya! Could you tell us which Android version you're using ? Thanks~

8.1

**Comment by RobbWatershed** [comment]
**Set up**
- Emulator with Android 8.1
- Fresh install of Hentoid v1.18.5

**Testing**
- Hentai2read : site is dead => no site = no problem 💀 
- Hentaifox
  - long press on a cover => works ✅ 
  - long press on a title => works ✅ 
- E-hentai
  - long press on a cover => works ✅ 
  - long press on a title => works ✅ 
  - long press on a link in comments => works ✅ 

**Conclusion**
Couldn't reproduce the issue => Closed

**Comment by Mrfiregem** [comment]
This seems to be a problem with Chrome's webview. Disabling Chrome or using a very old version (e.g. v79) doesn't cause this issue, but using the latest one (v117 does)

**Comment by Zkeikk** [comment]
I have this same issue after getting a new tablet. Tried disabling chrome but the issue persists.
