### ISSUE TITLE
Issue with Shortcut to Open the Library 

### ISSUE THREAD

**Issue by locuturus** [avluis/Hentoid#1083]
**Hentoid Version**: v1.18.0 (657)

**Device/Android Version**: Xperia 5 iii / A13

**Issue details / Repro steps**: Settings > Storage > Storage management > 3dot > Open folder

**Stack trace / LogCat**:
There is no error message. If my library is in public device storage then this shortcut works. But if I store the library inside a content provider, for example Anemo on GitHub by 2bllw8, then the intent created by that shortcut fails to open Anemo's content provider and DocumentsUI fails back to opening the default Downloads content provider.

The intent:
![Screenshot_20230727-210139](https://github.com/avluis/Hentoid/assets/19397973/e228729a-6a46-4bfe-852e-ba1f5e2230c6)

I'm not following the logic for the repeated folder path at the end of the data string but no matter, I haven't found a way to adjust the parameters to make this work. The Anemo app itself can open it's own content provider root in DocumentsUI but I can't intercept the intent it's using to do it.

It should open the .hentoid folder within this content provider:
![4r7g517k2h9ys1wy](https://github.com/avluis/Hentoid/assets/19397973/e761c33d-35ea-424c-a279-c43d3c1ce317)

By the way other content providers like Termux's also fail to open with this style of intent. It works well for content://com.android.externalstorage paths, but not content://3rd.party.app paths. I don't know why, but I'm hoping you all can figure it out!

Regards.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
@locuturus I've just taken a look at Anemo, which hasn't been updated for one entire year. Is that issue still worth investigating?

**Comment by locuturus** [comment]
Anemo is not a feature rich app, it could easily go for a while without needing attention. But even if it is abandoned the larger problem is building an intent that can open a 3rd party content provider. 

Several of Android's own content providers can be opened via intents, but none of those have a regular file structure so opening their root is the best I can do with Images, Videos, Audio, Documents, Downloads. But some providers, like Anemo, do use an internal file structure that is apparent in the intent created when opening some file within the provider.

Because Anemo is open source I hoped you could learn how it works and see if it can be done with an intent at all — or if it can only be done with some method Hentoid can't reasonably implement.

**Comment by RobbWatershed** [comment]
Spend a little time playing with Anemo. Here's what I understood so far :
- The URI is not to blame - Hentoid actually plays well with Anemo for the rest of its features, which means it does store and use valid URIs that Anemo recognizes
- `android.intent.action.VIEW` should be the Action to use to open a file or folder
- Anemo doesn't have any receiver for `android.intent.action.VIEW` (see [its manifest](https://github.com/2bllw8/anemo/blob/main/app/src/main/AndroidManifest.xml) which only captures "share" / "send to" intents)
- The Intent Hentoid builds doesn't actually open Anemo; it opens the Android file picker, which in turn frowns and says "wtf is that URI?!"

![image](https://github.com/user-attachments/assets/b228f877-74df-4eaa-a824-1006daf738f9)

That leaves two possibilities :
- Anemo hasn't been built to be opened on a specific folder though an Intent
- There's something missing somewhere, for the Android file picker to be able to understand the given URL has to be interpreted by Anemo

**Comment by RobbWatershed** [comment]
Trying to debug what happens on DocumentsUI gives me that warning :
![image](https://github.com/user-attachments/assets/dec9bf3b-7c2a-4d9b-8cc6-750fd32ed163)

That basically means that Anemo itself doesn't behave like the file picker would expect a compliant documents provider to...hence the problem we observe.

I'd say what you're trying to accomplish simply can't work; at least with Anemo.

**Comment by locuturus** [comment]
Cool, thanks for tracking that down. I guess the file provider has to support folder opening via intent like you say. Anemo can do this itself, but it must be a private function.

**Comment by RobbWatershed** [comment]
I'm pretty sure Anemo could work that out if the repo were active, but it doesn't seem to be so.

Is there anything else I can do regarding that issue?

**Comment by locuturus** [comment]
No, I think it's entirely on the provider like you say.
