### ISSUE TITLE
Unable to download from exentai / download error from exhentai

### ISSUE THREAD

**Issue by GarenNasus** [avluis/Hentoid#1090]
**Hentoid Version**:
1.18.1

**Device/Android Version**:
12

**Issue details / Repro steps**:
All images in the Exhentai gallery are not downloaded, displaying Network Error. Hitomi down is normal. This error is not temporary and occurs continuously. The download function is normal for a short period of time and then fails again, but I don't know why

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
[Networking]: Network error; HTTP statusCode=0; message=Invalid mime-type received from https://exhentai.org/fullimg.php?gid=954791&page=56&key=97s58mya2pu (size=0.00) @ 

@AVnetWS/admin-team

**Comment by GarenNasus** [comment]
![Screenshot_20230818_035208_Hentoid](https://github.com/avluis/Hentoid/assets/142536618/d2ab1959-9584-4e94-9eaa-17b4c09d500d)

**Comment by RobbWatershed** [comment]
First things first, thanks for posting the log 🙃 

This isn't a general issue as ExH hi-res pictures downloads works fine on my side. 

Considering e-h / exH have put limitations to how much you can download in one day, you might have reached your daily limit, especially, if you download as many full res pages as you posted in your screenshot.

![image](https://github.com/avluis/Hentoid/assets/35880555/0ef9754f-eb29-493e-b444-fb6814a56497)

Source : https://ehwiki.org/wiki/My_Home

I advise you to wait for 24 hours and see if the situation gets better. If you're in a big hurry, you may try getting these books using the torrents provided by exH.

**Comment by GarenNasus** [comment]
Thank you for your reply. But I don't think that's the cause of the problem. I know EXH has set a download limit, and I haven't reached the download limit. Also, I've been having this problem for more than 5 days and haven't been able to download one in the meantime
![Screenshot_20230818_043431_Hentoid](https://github.com/avluis/Hentoid/assets/142536618/d1a13a7a-7b99-4927-89fe-59f92967bfb5)

**Comment by GarenNasus** [comment]
I have new information. Problem only occurs in certain galleries, not in whole EXHen. And if you change the download method to 'download while reading', the number of pages is recognized, but the page is not downloaded, so an error occurs. At this time, when you click 'reanalyze the work', it says you can't find the image.

**Comment by GarenNasus** [comment]
I found a better clue. Errors do not always occur when downloading from a particular gallery. An error occurs when you enable the 'Download at High Resolution' feature in the download settings. When you see signs with low resolution often downloaded, you can expect the following. When downloading a high-resolution image in an environment where the Internet connection is not fast, the application judges it as an error and marks it as a "network error" and passes the download of the image.

**Comment by RobbWatershed** [comment]
Thanks for your detailed feedback.

That issue is clearly linked to hi-res pictures downloads, yes. However, the error message you got has nothing to do with connection speed - it means the exHentai server served an empty stream instead than an image. If it isn't linked to your image limit, then it might be some for of anti-leech mechanism.

I wonder if using the app's download speed limiter would work for that case. Could you try setting it to, say, 400 KBps and see if it still happens?

**Comment by GarenNasus** [comment]
I got an error both when I didn't use the app download speed limiter and when I used it and set the setting to 100, 200, 400, 800kb. And this is information that can be helpful. A comparison between a normal gallery download and an error-prone gallery download. You can see that the speed is very low when an error occurs.
![Screenshot_20230821_014044_Hentoid](https://github.com/avluis/Hentoid/assets/142536618/b597ee7e-6213-4d8d-8898-075fd5614cb5)
![Screenshot_20230821_014012_Hentoid](https://github.com/avluis/Hentoid/assets/142536618/b04676e3-ef64-49c6-9654-d58829a23397)

**Comment by RobbWatershed** [comment]
Thanks for the feedback. Could you send me the full name of an error-prone gallery?

**Comment by GarenNasus** [comment]
Name : [ANIM Mother & Wife] Itsumademo Musuko no Mama ja Irarenai! 3 ~Kyonyuu de Muchimuchi na Kaa-san no Oppai o Sutte Monde Hasande Ippai Dashitai!~

Arist:Hodumi_Kaoru

You can find it easily by searching by author name.
Errors also occur in galleries of works in the series such as this game.

**Comment by RobbWatershed** [comment]
I managed to repro that issue on my side.

Here's what the exHentai server actually returns : `Downloading original files of this gallery requires GP, and you do not have enough.`

=> We've been focusing on **image limits** so far, but we should've considered **Gallery Points** as well 😅  Can you check if your GP count is low when you encounter that problem?

**Comment by GarenNasus** [comment]
I haven't done any activities, so I won't have a GP. Come to think of it, from the end of July, galleries that are more than a year old must consume GPs, and I think this is the problem. The original quality gallery that I recently downloaded well was just uploaded. I think I misunderstood because the cause of the error was only the network.

**Comment by RobbWatershed** [comment]
> Come to think of it, from the end of July, galleries that are more than a year old must consume GPs, and I think this is the problem

That must be it. Thanks for clarifying!

> I think I misunderstood because the cause of the error was only the network

Understandable; I did the same at first.

I've modified the app to make such problems more explicit rather than just displaying a network issue.
