### ISSUE TITLE
New source : Anchira.to

### ISSUE THREAD

**Issue by srcsvl** [avluis/Hentoid#1106]
I saw that ksk.moe opened again, do you have any chance to add it?

Site:[ksk.moe](https://anchira.to/)

**Comment by RobbWatershed** [comment]
Anchira doesn't have the same technical layout as KSK. Replugging Hentoid won't work out of the box.

I won't lose any more time working on it to see the site being shut down one week later.

Let's put it to the next community voting and see if it survives until then.

**Comment by mish20011** [comment]
> Anchira doesn't have the same technical layout as KSK. Replugging Hentoid won't work out of the box.
> 
> I won't lose any more time working on it to see the site being shut down one week later.
> 
> Let's put it to the next community voting and see if it survives until then.

i honestly prefer if it stays a secret at this point so it wont get nuked much sooner

**Comment by RobbWatershed** [comment]
We just held a vote on Discord, and the community decided to replace devianart with anchira for v1.18. 

=> Support will be added soon.
