### ISSUE TITLE
About the function

### ISSUE THREAD

**Issue by warkene2** [avluis/Hentoid#1112]
▽I would like to see two-page display added to the viewer function.  When viewing a single page on a 10-inch or larger tablet, the image is too wide when viewed vertically and is wasted when viewed horizontally.

▽Why can only one external library be registered?

The doujinshi folder, manga folder, and image folder are all in different locations, but you can only select one, which is currently inconvenient.

▽I ​​would like to be able to set the display of cover thumbnails up to 6 columns horizontally (I don't really want this, but...)

**Comment by RobbWatershed** [comment]
Thanks for your feedback, but posting an all-purpose issue with multiple sub-issues inside doesn't make things easy for me 😅 

If you have other ideas, please submit **one Github issue per idea** so that we can track and order them as tasks when we agree.


> ▽I would like to see two-page display added to the viewer function.  When viewing a single page on a 10-inch or larger tablet, the image is too wide when viewed vertically and is wasted when viewed horizontally.

Are you talking about that? https://github.com/avluis/Hentoid/issues/623

> ▽Why can only one external library be registered?

> The doujinshi folder, manga folder, and image folder are all in different locations, but you can only select one, which is currently inconvenient.

Why not... In the meantime, I advise you to put them all on the same location ;)

> ▽I ​​would like to be able to set the display of cover thumbnails up to 6 columns horizontally

Doesn't the new features from v1.18.8 allow you to do that? 

> (I don't really want this, but...)

I don't get that part. We don't do theoretical features that look good on paper but aren't used by anyone - we do things that are actually useful. Do you need that feature?

**Comment by warkene2** [comment]
Sorry for not following the posting rules

▽Is it correct to understand that the addition of double-page spread functionality has been considered for three years and there are plans to implement it?
With this, you can wait with peace of mind.

▽If you put all kinds of files in one folder, won't it be difficult to see when you open the folder with something other than Hentoid (such as Windows Explorer), making management complicated?

▽Column
Library/Grid View Customization → Setting the Bbook display width to S or M was sufficient.
Sorry for the lack of research.

**Comment by RobbWatershed** [comment]
> ▽Is it correct to understand that the addition of double-page spread functionality has been considered for three years and there are plans to implement it?
> With this, you can wait with peace of mind.

It's absolutely correct, as we tend to priorize features that are asked by many people, or fit well with each other. Double-page has been there for a while without anyone to +1 it. All I can say for now is "it will be eventually added" 😄 

> ▽If you put all kinds of files in one folder, won't it be difficult to see when you open the folder with something other than Hentoid (such as Windows Explorer), making management complicated?

Not necessarily, if you keep meaningful subfolders (e.g. external/doujins, external/mangas, external/images)

> ▽Column
> Library/Grid View Customization → Setting the Bbook display width to S or M was sufficient.

Glad to read that 👍 

> Sorry for the lack of research.

No problem man
