### ISSUE TITLE
Storage saving options

### ISSUE THREAD

**Issue by Draegon366** [avluis/Hentoid#1115]
I know that cloud storage is low priority, but I think it would be a good idea to have an option to only download favourites while keeping other doujins I undownloaded in the library for easy access.

also not sure how much discussion has gone into the cloud storage, but if it is implemented, there should Abe a way to store only non favourites on the cloud and favourites stored locally.

I have 50gb of doujins downloaded and can't keep any games on my phone...

**Comment by RobbWatershed** [comment]
Do you know about the streamed books feature?

When you select a book and select the "Switch to streaming" menu, the book stays in your library but doesn't store any images anymore : they're fetched online as you read them.

Wouldn't that help you freeing your storage?

NB1 : Doing a backup of these books is always a good idea in case their source disappears
NB2 : Don't try this with Hitomi, their image hosting changes over time, which makes streaming complicated

> I have 50gb of doujins downloaded and can't keep any games on my phone...

Then you're a true Man of Culture - congrats 😉

**Comment by Draegon366** [comment]
No I didn't know about that, it helps a lot. I'm trying to back my library up, though google drive seems to struggle with receiving all the doujins.

Would it be possible for you to create a feature to enable streaming for specific tags or groups automatically?

**Comment by Draegon366** [comment]
Why is there a limit for streaming 1000 books at once? I have uhh, 4000 to stream..

**Comment by RobbWatershed** [comment]
> Would it be possible for you to create a feature to enable streaming for specific tags or groups automatically?

I'm adding it to #992 as we speak

> Why is there a limit for streaming 1000 books at once? I have uhh, 4000 to stream..

That's a dumb technical limitation of Android I can't bypass. You'll have to do it four times 😋

**Comment by RobbWatershed** [comment]
Closed as the feasible part of the request has been created as an issue (#992)
