### ISSUE TITLE
Reading from a nas/smb?

### ISSUE THREAD

**Issue by kaisen7887** [avluis/Hentoid#1116]
Hello. Just a suggestion, are there plans for having an external Library from nas/smb share folder to read from similar to komanga or vlc? It will be nice if it will be a feature in the future as it is hard to store libraries with 64gb of storage(mostly full of games.).

Btw I love the achievement section you guys added. I just got the serial reader achievement after the update.

**Comment by RobbWatershed** [comment]
NAS/SMB support has been discussed - we came to the conclusion that Hentoid will support whatever pops in the Android folder selector, but won't have its own internal connector for SMB / NAS / WEBDAV / whatever other protocol.

If you want to get such support, try finding a 3rd party app that adds it to the Android folder selector.

PS : I'm glad you appreciate the achievements :D
