### ISSUE TITLE
Anchira download eror

### ISSUE THREAD

**Issue by srcsvl** [avluis/Hentoid#1117]
**Hentoid Version**:1.18.9(691) 
**Device/Android Version**:Samsung Galaxy S23 Ultra

Eror Log:

Error log : begin
Hentoid ver: 1.18.9 (691)
API: 33
Device: SM-S918B
Start : 2023-11-14T21:29:34.556Z
End : 2023-11-14T21:29:34.556Z (00:00)
-----
Error log for Patience is a Virtue [@Anchira] : 1 errors
2023-11-15T00:29:34.556 Image list - [Parsing]: No images have been found. Error = null @ /12304/b5657a54f571
Error log : end

**Comment by RobbWatershed** [comment]
Anchira changed -intentionally or not, I'm not certain- the way their site works, which causes Hentoid to fail.

I've already identified a quick way to fix it, and a much slower way as a plan B.

I'll try the quick way very soon and see how it goes

**Comment by RobbWatershed** [comment]
Fixed in today's v1.18.10

The site owner being in an active phase of development, the site rapidly changes and may break compatibility with Hentoid multiple times in the following weeks. We're doing what we can too keep the pace. Thanks for your understanding 😉
