### ISSUE TITLE
Anchira.to download button is currently broken

### ISSUE THREAD

**Issue by Kantotero** [avluis/Hentoid#1119]
It says download is currently broken. I was able to download just fine a few days ago. Also it immediately crashes and the app restarts whenever I press anchira

**Comment by RobbWatershed** [comment]
Thanks for your feedback.

We're aware of the situation, as stated in the latest release notes : https://github.com/avluis/Hentoid/releases

A new fix is currently being developed

**Comment by RobbWatershed** [comment]
Site dev is constantly playing cat & mouse with every update. Expect the app to regularly start and stop supporting Anchira until one of us gives up. I can't promise nor schedule anything in that regard
