### ISSUE TITLE
Hitomi download not possible.

### ISSUE THREAD

**Issue by mkjang2000** [avluis/Hentoid#1120]
**Hentoid Version**:
1.18.12

**Device/Android Version**:
Galaxy Z Fold4 / Android14 / One Ui 6.0

**Issue details / Repro steps**:
1. Run the app.
2. Select and access Hitomi.
3. Press the automatic language setting button (set to Korean).
4. Download is not possible when trying

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

I'm using this app, but I can't download any works.
When I try to download a work, only the message "This work cannot be downloaded. Sorry~" appears and nothing is downloaded. It's difficult because no log files are created either.

https://github.com/avluis/Hentoid/assets/26732059/2a7b5164-8402-40f4-b4d9-d7e1a430007b

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
It does work on my side. If you're using a VPN, double-check your settings.

**Comment by RobbWatershed** [comment]
Thanks. I've found your phone on the central log and it appears we introduced a regression on v1.18.12. It's been fixed and will be released soon.

**Comment by mkjang2000** [comment]
Confirmed. Thank you!
