### ISSUE TITLE
further application of metadata for external library

### ISSUE THREAD

**Issue by sadboy889** [avluis/Hentoid#1127]
it would be great if the app can scrap metadata from online sources for external libraries, mass scan the missing metadata and fill the missing tags/artist automatically

**Comment by RobbWatershed** [comment]
Hi and thanks for your feedback!

That's a good idea that has already been logged as #770.

I'm closing that issue as a duplicate.

**Comment by sadboy889** [comment]
maybe it would work easier for the app to integrate with hentag?

**Comment by RobbWatershed** [comment]
Sounds like a good idea! I'm adding that to #770. Thanks for the suggestion
