### ISSUE TITLE
New source:novelcrow

### ISSUE THREAD

**Issue by srcsvl** [avluis/Hentoid#1128]
Site:www.novelcrow.com
The site is generally up-to-date and I would like to see if it is possible in practice

**Comment by RobbWatershed** [comment]
My antivirus has just blocked that site upon trying to reach it.

I've opened it on a mobile browser and saw it's riddled with intrusive ads (i.e. banners, widgets, agressive pop-ins).

Not sure we want to add that kind of source 🤔 

Can you give me a few examples of books that are only available there, and not on any of our existing sources ?

**Comment by srcsvl** [comment]
There are original and uncensored manga available in Irodori and Fakku

**Comment by RobbWatershed** [comment]
Greenlit in #1169
