### ISSUE TITLE
Inquiry Regarding Camera Permission

### ISSUE THREAD

**Issue by ghost** [avluis/Hentoid#1129]
**Hentoid Version**: latest

**Device/Android Version**: Android 11

**Issue details**: 
I've noticed that your app has the ability to access to the camera, and I'm curious about the reasons behind this permission. Could you please provide some information on how the camera feature is utilized within the app and what specific functionalities or benefits it brings to the user experience?

**Image**

[![IMG-ScreenShot.jpg](https://i.postimg.cc/L4jGHs1B/IMG-20240119-193628.jpg)](https://postimg.cc/MXK95qtv)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Hi there,

I understand your concern. That permission is only used if you enable biometric authentication through privacy settings.

**Comment by whitesparrow294** [comment]
Thnx for the information. To avoid confusions in future please add that to the FAQ section in the readme.

**Comment by RobbWatershed** [comment]
Done!
