### ISSUE TITLE
Luscious site picture set have reverse order 

### ISSUE THREAD

**Issue by bloodsucker3011** [avluis/Hentoid#1130]
Luscious site, only in picture (never ran into problem with comics section) set album have reverse order (end of page com first). When in the website when sort by newest the order is right
-->

**Hentoid Version**:

**Device/Android Version**

Link sample 
https://members.luscious.net/albums/huayang069-zhu-ke-erbooty_439450/

**Comment by RobbWatershed** [comment]
Hi and thanks for your feedback.

I'm not sure about what the problem is :
- Are you describing an order issue when browsing the Luscious website with Hentoid?
- Are you describing an order issue when downloading Luscious galleries with Hentoid?

**Comment by bloodsucker3011** [comment]
I described the order issue after downloading luscious picture set with hentoid. And only problem with picture set, manga section is fine. My guess is luscious have new features only for picture set is "rate picture" and what it does is reverse order of album 
![Uploading Screenshot_20240127-082403~2.png…]()

**Comment by bloodsucker3011** [comment]
![Screenshot_20240127-082310~2](https://github.com/avluis/Hentoid/assets/28969855/a5ae26b6-0ad2-41f4-acc4-dff397cd23f5)

**Comment by bloodsucker3011** [comment]
![Screenshot_20240127-082403~2](https://github.com/avluis/Hentoid/assets/28969855/d838df13-acae-4c4a-bfff-4b320d8cbb5c)

**Comment by RobbWatershed** [comment]
Thanks you for the detailed report. The issue has been fixed and the fix will be available on next release.

**Comment by RobbWatershed** [comment]
Available on today's v1.19.0

**Comment by bloodsucker3011** [comment]
Thank, I look forward it
