### ISSUE TITLE
Can't Delete empty books 

### ISSUE THREAD

**Issue by Padpoy** [avluis/Hentoid#1144]
When downloading a book from Specific artist Jabuk may contain multiple groups and it causes a lot of Clutter
 so What I usually do i edit the books and the remove the group or the artist  from the  metadata 
And that resulted in Empty groups or arts I tried to delete it but it won't it will just stay there empty increasingly the clutter of the Interface
By the way I can't enter The discord server I don't know Why

**Comment by RobbWatershed** [comment]
No more information from the OP => issue closed
