### ISSUE TITLE
Always Has Blank White Page

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1146]
I just wanted to share there's a bug after the latest 4 timss update the bug still there even after i got latest update. Whenever i open NH it always becomes blank page when i press the tag for searching artist or specific genre.

Temporary problem solved that i know.

1. Press the genre back and forth it will stays blank page but if u press 2-3 times it will becomes normal sometimes it doesn't.

2. Go to random book then try to open it. If the book open normally which means u can press the tag button to search specific tag

![Screenshot_20240304-063306](https://github.com/avluis/Hentoid/assets/37593430/e2563e96-8c7e-4aea-bd2d-f991bb36b09a)

Device: Infinix Note 11
Update: v1.19.3

**Comment by RobbWatershed** [comment]
Hi there,

If it only happens on NH, it's their ad system that's to blame : when you navigate the site without any adblocker, you'll have a pop-in that takes up the entire screen. I haven't found the way to remove it entirely; it just displays a white screen instead of the advertisement itself.

If it happens on multiple site, I'd like to know which ones.

Thanks~

**Comment by dudino88** [comment]
Got the same issue with hitomi. iam on the latest update.

**Comment by ghazzor** [comment]
I have the same issue but my pages are stuck at a black screen

**Comment by RobbWatershed** [comment]
@dudino88 @ghazzor  Thanks for your feedback too. Could you tell me precisely :
- Which sites it happens for
- Which sites it doesn't

Just satying "Hitomi" or "NH" doesn't really help 😅

**Comment by ghazzor** [comment]
> @dudino88 @ghazzor  Thanks for your feedback too. Could you tell me precisely :
> - Which sites it happens for
> - Which sites it doesn't
> 
> Just satying "Hitomi" or "NH" doesn't really help 😅 

Nhentai ig , did not test other sites
Well nhentai opens other pages and redirects you to a add site and that is the issue with the app I think , it can't  handle redirects properly 

The above mentioned two has frequent redirects , others probably have the same issue

Will test all sites and report

**Comment by dudino88** [comment]
> @dudino88 @ghazzor Thanks for your feedback too. Could you tell me precisely :
> 
> * Which sites it happens for
> * Which sites it doesn't
> 
> Just satying "Hitomi" or "NH" doesn't really help 😅

i use only hitomi and e-hentai. e-hentai works without problems on hitomi i only see a white page nothing more.
![20240305_174800](https://github.com/avluis/Hentoid/assets/162194751/f40c8482-4c9e-4660-b1d5-25521b29c4a7)
![20240305_174749](https://github.com/avluis/Hentoid/assets/162194751/5919b2c3-7f2b-4306-b590-f1bf387ff962)

**Comment by dudino88** [comment]
Just wanted to say I've updated my android and now everything works like always.
Chrome v100/API29
H v1.19.5

**Comment by ghazzor** [comment]
Yea this is fixed , this can now be closed

**Comment by RobbWatershed** [comment]
Thanks for your feedback @ghazzor @dudino88
