### ISSUE TITLE
The native add-tag list no longer appears in order and cannot maintain a filter

### ISSUE THREAD

**Issue by GoonLight** [avluis/Hentoid#1150]
**Hentoid Version**: v1.19.5

**Device/Android Version**: Samsung Galaxy S9+

**Issue details / Repro steps**: I encountered this first bug with the Hebtoid native add-tag menu a number of months ago. I'm unsure of which version. Under normal operation you could select a specific category to add a tag from (like "Author" or "Tag") before tapping the plus sign to bring up the add-tag menu in a filtered state. The issue is once you add a single tag it will unselect the filter. Meaning as you scroll you would get clumps of "author" tags or "character" tags when previously you'd filtered for "Tag" tags. I do not have a screenshot of this as the problem has escalated. 

When I updated from v1.19.3 to v1.19.5 the issue changed to the entire tag list being out of order, no longer organizing itself by the number of instances of each individual tag within your library, sub organized alphabetically. There does seem to be some correlation to number of tags, but no recognizable pattern. This can be seen in my first screenshot. On top of that when a tag is selected from the list the filter is still removed, but rather than presenting as clumps of the different tag categories they are mixed together in a near unparsable mess. This is shown in the second screenshot. 

![Screenshot_20240328-144525_Hentoid](https://github.com/avluis/Hentoid/assets/165319736/abaca2ad-3725-45f8-981d-67198ffb3e84)

![Screenshot_20240328-144546_Hentoid](https://github.com/avluis/Hentoid/assets/165319736/84f7dd14-aa64-4ab3-81a6-f484adf5cae0)

The only current workaround I've found is to constantly close the add-tag list and reselect the filter, though this only fixes the different types of tags being mixed together and not the out of order listing.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Issue has been fixed. The fix will be available for next release

**Comment by RobbWatershed** [comment]
Available in today's v1.19.6
