### ISSUE TITLE
Anchira downloads are currently broken

### ISSUE THREAD

**Issue by ErXxYLxX** [avluis/Hentoid#1151]
The site download isn't working on Hentoid v1.9.5(722)

**Comment by RobbWatershed** [comment]
Trying to support Anchira has been an  excruciating struggle. It's not planned for the time being.

If you need anything, download the archive manually and load it using Hentoid's [external library](https://github.com/avluis/Hentoid/wiki/Using-the-external-library).

**Comment by ErXxYLxX** [comment]
Ok, thanks!
