### ISSUE TITLE
Downloader can't find last page

### ISSUE THREAD

**Issue by callmeTayyy** [avluis/Hentoid#1159]
**Hentoid Version**: 1.19.5 (722)

**Device/Android Version**: Samsung A54 5G (SM-A546E/DS) / Android 14, One UI 6.0

**Issue details / Repro steps**: When I download some *doujins* from ExHentai, ~the downloader thinks that~ one page is missing and it gives an error. ~**Important:** **all the pages are downloaded just fine**~, the *book* stays in the downloder instead of going to the library.

I could not identify a pattern, this doesn't happen with all books from ExHentai. Here are more details:

* I download the hi-res versions of the books
* I'm logged in the ExHentai account
* I think this starts to happen after the 1st download of the session/day, but I could not test to verify
* ~When I inspect the download, all pages are there~
* Nothing changes if I try to re-download from scratch

**Expected behavior:** The download finishes and is placed in my library.

**Stack trace / LogCat**:
```ruby
Error log : begin
Hentoid ver: 1.19.5 (722)
API: 34
Device: SM-A546E
Start : 2024-05-02T01:45:17.531Z
End : 2024-05-02T01:45:18.358Z (00:00)
-----
Error log for [GraniteMcGee] Big Surprise [2876245@exhentai] : 2 errors
2024-05-01T22:45:17.531 17 - [Networking]: Network error; HTTP statusCode=0; message=failed to connect to lotxjma.lleoognhlbfi.hath.network/47.152.199.52 (port 49584) from /<IP> (port <port>) after 4000ms @ https://exhentai.org/fullimg/2876245/17/0x4kkb0a7i1/big_surprise_page_16.png
2024-05-01T22:45:18.358 pages - [Parsing]: The number of downloaded images (46) does not match the book's number of pages (47) @ https://exhentai.org/g/2876245/2f64f2c6de
Error log : end
```

![20240501_231356](https://github.com/avluis/Hentoid/assets/81816463/2d4b9c42-a79f-4a1b-bd45-09211c161218)

Notice above that ~it thinks~ all these books are missing one page.

https://github.com/avluis/Hentoid/assets/81816463/288d5fa5-dfc5-4453-9e2a-b924ea4f1eb1

If the option to 'Automated download retries' is selected, the downloader gets stuck in a loop forever.

@AVnetWS/admin-team

**Comment by callmeTayyy** [comment]
The thing is, all the pages were downloaded, I can view all them all.

I just tried it and got the same error, but the domain is different:

```ruby
Error log : begin
Hentoid ver: 1.19.5 (722)
API: 34
Device: SM-A546E
Start : 2024-05-10T15:43:53.633Z
End : 2024-05-10T15:43:54.591Z (00:00)
-----
Error log for [GraniteMcGee] Big Surprise [2876245@exhentai] : 2 errors
2024-05-10T12:43:53.633 17 - [Networking]: Network error; HTTP statusCode=0; message=failed to connect to tcrbtxc.lleoognhlbfi.hath.network/47.152.199.52 (port 49584) from /192.168.100.188 (port 52276) after 4000ms @ https://exhentai.org/fullimg/2876245/17/kxggp01a7nr/big_surprise_page_16.png
2024-05-10T12:43:54.591 pages - [Parsing]: The number of downloaded images (46) does not match the book's number of pages (47) @ https://exhentai.org/g/2876245/2f64f2c6de
Error log : end
```

PS: redownloading from scratch doesn't fix it.

**Comment by callmeTayyy** [comment]
Update: I got confused, the page is indeed missing. Sorry about that.

**Comment by RobbWatershed** [comment]
Okay, I have bad news for you :
- Downloading the book from my end (western EU) works fine with the hi-res images option on. All of them have been successfuly downloaded
- When I try to manually load the one you just reported (`https://exhentai.org/fullimg/2876245/17/kxggp01a7nr/big_surprise_page_16.png`), it works as well

=> The problem seems to be on your end. Maybe try accessing exH from another network, or with a VPN?

**Comment by callmeTayyy** [comment]
Sorry for taking so long to reply.
You are right! Using a VPN solved my issue, I still don't understand why this happens with some pages and not others but that's besides the point.

As a side note, resuming the download with VPN turned on doesn't work as the app don't download the missing pages but, on the other hand, re-downloading from scratch does work. I should open a separate issue about this.

Thank you for taking the time to look into this.
