### ISSUE TITLE
Low quality / picture resolution when viewing or downloading picture from Exhentai

### ISSUE THREAD

**Issue by kingWelkin** [avluis/Hentoid#1161]
Exhentai has changed its auto resolution to 780px from 1280px which make the downloaded and browser pictures as low quality. Settings on Exhentai for resolution also didn't work. Desktop browsers can get higher resolution with auto resolution than mobile browsers.

**Comment by RobbWatershed** [comment]
You can still use the "download hi-res picture" setting, don't you?

I'm not certain I understand what you need. Should we investigate to see why exH settings for resolution have no effect on the resolution of downloaded images?

**Comment by kingWelkin** [comment]
Yes I can use the hi-res option but the image is way too big.

Otherwise, I can only get really low resolution. The auto resolution set by mobile browsers.

The auto resolution by desktop browsers 1280px, will do.

**Comment by RobbWatershed** [comment]
I'll see what I can do

**Comment by RobbWatershed** [comment]
> Settings on Exhentai for resolution also didn't work.

I just used them to force the resolution to 1280 and it worked like a charm.

Did you push the tiny "Apply" button at the very bottom of the settings screen?

**Comment by RobbWatershed** [comment]
No answer for 3 weeks => I assume there's no issue anymore

All hail the "Apply" button

![cgr2seven01](https://github.com/avluis/Hentoid/assets/35880555/0d9f58e3-b85a-450b-b184-0e79232bfbfb)
