### ISSUE TITLE
Storage External Library Issue

### ISSUE THREAD

**Issue by AttsTom** [avluis/Hentoid#1174]
**Hentoid Version**: 1.19.10

**Device/Android Version**: Samsung S20+/Android 13

**Issue details / Repro steps**:
In Samsung's hidden apps mode, it is not possible to select any directory as the external library's source (Returns "Primary and external locations must have seperate folder" EVERYWHERE INCLUDING OUTSIDE AND INSIDE BASE FOLDER). This could be due to the fact that the app doesn't require permission ot access all files (?). Maybe a temporary solution would be the ability to manually import an archive into the library.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

https://github.com/user-attachments/assets/fdf3921e-4874-44e5-bada-04cd4c0d7cef

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for the vid. It shows you're selecting .Hentoid/Downloads as an external library location, which is obviously forbidden.

External library root folder should be created at least one level higher (e.g. myFolder/.Hentoid/external or even myFolder/external)

**Comment by AttsTom** [comment]
> Thanks for the vid. It shows you're selecting .Hentoid/Downloads as an external library location, which is obviously forbidden.
> 
> External library root folder should be created at least one level higher (e.g. myFolder/.Hentoid/external or even myFolder/external)

Unfortunately it gives me the same error even if I create a folder in the root folder.

**Comment by RobbWatershed** [comment]
> Unfortunately it gives me the same error even if I create a folder in the root folder. Would it be possible to have a button asking permission to access all files? I believe this has to do with Samsung's Secure Folder feature restricting apps' access to files within the folder itself.

I'll see what I can do

> I've also recently denied Hentoid's access to its own downloaded files by accident when I tried to give the app permissiom to other folders. It's currently impossible to revoke that nor find a way for Hentoid to ask for permission again.

Just reinstall the app from scratch

**Comment by RobbWatershed** [comment]
> Unfortunately it gives me the same error even if I create a folder in the root folder. Would it be possible to have a button asking permission to access all files? I believe this has to do with Samsung's Secure Folder feature restricting apps' access to files within the folder itself.

That problem should be solved with next release ✅  Folders should also be displayed with a proper path instead of just "/"

**Comment by RobbWatershed** [comment]
Should be fixed with today's v1.19.12

**Comment by AttsTom** [comment]
THANK YOU 🙏🙏
