### ISSUE TITLE
Archive progress notification shows wrong percentage

### ISSUE THREAD

**Issue by TheGistGuy** [avluis/Hentoid#1176]
**Hentoid Version**: v1.19.10 (741)

**Device/Android Version**: Android 11

**Issue details / Repro steps**: Try to archive a large book. Hentoid will report the archival progress in your notifications. The percentage in the notification message will go from 0% to 1% instead of 0% to 100%, e.g. 55% will be reported as 0.55%.

**Stack trace / LogCat**: -

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
You're totally right - and the STOP button is unusable too.

Thanks a lot for your feedback!

**Comment by RobbWatershed** [comment]
Available in today's release
