### ISSUE TITLE
Suggestions: Bulk Download Only CODE in NH

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1177]
I just wanted to share some suggestions can u make bulk download using code on NH?

For example: 

Most of the time i found many doujin on my Facebook but it just bunch of code on NH but it's kinda takes to long to repeatly watch the code and put it on website (Hentoid apps).

Can u add the option on NH only to just download using code and bulk download?

**Comment by RobbWatershed** [comment]
You currently have two ways to do that for NH :
- Queue screen > top right > Impot Downloads > Load a TXT file with an NH launch code on every line
- Settings > enable "Text select menu" > select the NH launch code wherever it appears your Facebook page > hit the Hentoid menu item

**Comment by Chocolalolz** [comment]
1. I did like what u said but it said "Invalid"
2. Cant open the txt menu files or i just do something wrong?

Here's the record i have

https://www.veed.io/view/72b0adc4-4919-4b31-93d0-d1d2b901341c?panel=

**Comment by RobbWatershed** [comment]
1. Make sure you load a raw TXT file, not a MS Word file or anything else + make sure there's a number on every line

3. Your video link doesn't work

**Comment by RobbWatershed** [comment]
No answer from the OP for one month => issue closed
