### ISSUE TITLE
[Feature request] Filter view for Downloaded Books and Streamed/Imported empty books

### ISSUE THREAD

**Issue by mish20011** [avluis/Hentoid#1194]
Having a huge library is becoming an issue, batch converting downloaded books into stream is quite difficult at times since some ehentai galleries get purged when you don't know. So I suggest a filter to view downloaded books only so that I can easily know which book I want to switch sources first before turning it into a streamed book (or else it will go to error section) rather than sorting by size to go to the very bottom just to see non-downloaded books

**Hentoid Version**: v.1.19.12

**Device/Android Version**:

**Issue details / Repro steps**:

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
There's already something that resembles what you need in advanced search, under the "Type" category
What you call "downloaded" is called "Folder". Streamed books are "Streamed".

**Comment by mish20011** [comment]
oh shit I did not know this, thank you so much, another question though, is there actually no way I could search a single tag for multiple sources using the advanced search? I always am left with choosing between ehentai or hentaifox to appear in my library and not together

**Comment by RobbWatershed** [comment]
The answer to your questions is :
> is there actually no way I could search a single tag for multiple sources using the advanced search? I always am left with choosing between ehentai or hentaifox to appear in my library and not together,

What you need is basically `TAG=xxx and (SOURCE=e-h or SOURCE=hentaifox)`

All of our search is AND-based, which means every tag you select or every term you type will add up to pinpoint less and less books. We do have an issue about making an OR-based search (#266), but it requires a huge amount of work, and there aren't that many users asking for it.

> maybe I don't know all the functions but is there a format to search for mulltiple tags in the search bar? I tried searching for tags like in nhentai (mother milf for ex.) but nothing shows

The search bar is a full-text search; it hasn't been designed to search specifically for multiple tags and sources. It just looks into every metadata for the text you type, and displays the results.

***

PS : I do appreciate your giving quality feedback over the years, but Github isn't exactly a forum - if you need to discuss other matters, either open a new Github issue, or ask away in the #help channel of our Discord. I won't reply in this issue anymore.
