### ISSUE TITLE
Scan new external archives, ignore older archives 

### ISSUE THREAD

**Issue by sadboy889** [avluis/Hentoid#1195]
close

**Comment by RobbWatershed** [comment]
Since version 1.19.17, external library automatically detects when you add or remove archives or folders and adds them to your collection. You normally don't need to rescan everything manually when adding new stuff in your external library.

**Comment by sadboy889** [comment]
> Since version 1.19.17, external library automatically detects when you add or remove archives or folders and adds them to your collection. You normally don't need to rescan everything manually when adding new stuff in your external library.

it doesn't detect new archives (one without json files) so you had to refresh location everytime you want to add it

**Comment by RobbWatershed** [comment]
I'm sorry if that doesn't work for you. I just tried adding an archive to my external folder; the app immediately detected it without having to reload.

I'll need to reproduce your issue to be able to fix it. Could you please : 
- Explain which version of Android you're using
- Explain what kind of archive you're loading
- Describe what you're doing step by step

Thanks in advance~
