### ISSUE TITLE
Read archive files from memory instead of temporarily extracting to internal storage

### ISSUE THREAD

**Issue by sadboy889** [avluis/Hentoid#1196]
close

**Comment by RobbWatershed** [comment]
If your need arises from your device having low specs, I _really_ doubt loading archives into memory will solve anything, expecially if your have 4 or 6GB RAM. Don't forget there are massive archives out there. I've seen 1GB+ hi-res pages crammed into a RAR.

By the way, temp files are uncompressed to a "controlled" cache that never exceeds 50MB (destroys oldest files when new ones are cached). If consuming 50MB on your storage is an issue to you, I strongly advise you buy a larger SD card or change your device.

**Comment by sadboy889** [comment]
> If your need arises from your device having low specs, I _really_ doubt loading archives into memory will solve anything, expecially if your have 4 or 6GB RAM. Don't forget there are massive archives out there. I've seen 1GB+ hi-res pages crammed into a RAR.
> 
> By the way, temp files are uncompressed to a "controlled" cache that never exceeds 50MB (destroys oldest files when new ones are cached). If consuming 50MB on your storage is an issue to you, I strongly advise you buy a larger SD card or change your device.

this explain better than me, https://github.com/mihonapp/mihon/pull/326

**Comment by sadboy889** [comment]
not my intention of comparing your app with others and asking you to mimic, there is no issue with your app at all

im just suggesting what i thought to be an improvement
