### ISSUE TITLE
bug report 

### ISSUE THREAD

**Issue by sp0614** [avluis/Hentoid#1198]
hentoid in my device is get bug,after i download it freeze and comeback to loading screen it happened multiple times

**Comment by RobbWatershed** [comment]
Could you please share tools> app logs > latest crash?

**Comment by sp0614** [comment]
latest-crash log : begin
Hentoid ver: 1.20.3 (751)
API: 31
Device: CPH2127
Start : 2024-11-05T18:54:10.506473Z
End : 2024-11-05T18:54:10.508325Z (00:00)
-----
Failed to allocate a 24 byte allocation with 2350648 free bytes and 2295KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 2350648 free bytes and 2295KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.setIndexInArray(SourceFile:614)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryTerminateWorker(SourceFile:905)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(SourceFile:863)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(SourceFile:806)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:754)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:707)

latest-crash log : end

**Comment by sp0614** [comment]
[Uploading latest-crash_log_20241106-0130.txt…]()

**Comment by sp0614** [comment]
![Screenshot_2024-11-06-02-01-43-26_8d485484d290ec17555e7acc83d01a83](https://github.com/user-attachments/assets/6c8cbf70-7d4c-404d-bd83-6a97356259d0)

**Comment by sp0614** [comment]
no update about my case yet?

**Comment by RobbWatershed** [comment]
It's a memory-related crash. Looks like your phone is loading too many things at once.

Try force-closing all your apps / restarting your device.

Does that happen only when downloading? Or when reading too?

**Comment by sp0614** [comment]
It happen only downloading

**Comment by RobbWatershed** [comment]
> It happen only downloading

In addition to what I suggested above, maybe also try lowering the number of parallel downloads to 2 or 4 (see downloader settings).

**Comment by sp0614** [comment]
ok, thanks for assist me
