### ISSUE TITLE
nhentai webview broken

### ISSUE THREAD

**Issue by propri** [avluis/Hentoid#1199]
**Hentoid Version**: Hentoid v1.20.3 (751) Chrome v130/ Android API 30

**Device/Android Version**: Samsung Galaxy Tab A / Android 11

**Issue details / Repro steps**: Opening any gallery on nhentai in the webview  
The image is displayed smaller than normal, and on the right side of the display. Also the search button is displayed in the wrong place. I am pretty sure this only occured after I updated the app last week. I am not sure which version I used before.

See ![hentoid](https://github.com/user-attachments/assets/a592f227-74bb-4987-b75b-04f88724e2e0)

For comparison in the browser: ![browser](https://github.com/user-attachments/assets/fbd9a137-dd39-4960-84ba-e338a5237c2e)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for your feedback. That issue has been fixed. The fix will be available on next release

**Comment by RobbWatershed** [comment]
Fix is available on today's v1.20.6
