### ISSUE TITLE
Bug Report After New Update

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#1201]
I got some app bug on the reader 

https://github.com/user-attachments/assets/52c30f57-75f0-4253-abcf-f385d3977bc5

Usually when i press either right or left side of the screen it will immediately change the page. Bur after i updated into latest update somehow it just messed up now it looks like has 1-2sec delay after pressing on corner

It just my opinion somehow after a few new update the apps getting buggier. Last time i encountered can't delete or download book now it has a few bug. The last 3 update is really buggy even it fix previous bug now it's getting new bug

**Comment by RobbWatershed** [comment]
Thanks for your feedback. We'll look into it.

> It just my opinion somehow after a few new update the apps getting buggier. Last time i encountered can't delete or download book now it has a few bug. The last 3 update is really buggy even it fix previous bug now it's getting new bug

Well, the reader is a complex component with dozens of different settings, and we have very few testers that accepted to take time and try out new builds. We're doing what we can with the resources we have. Sorry if your free software gets buggy sometimes.

**Comment by RobbWatershed** [comment]
> Usually when i press either right or left side of the screen it will immediately change the page. Bur after i updated into latest update somehow it just messed up now it looks like has 1-2sec delay after pressing on corner

Should be fine with next update

**Comment by RobbWatershed** [comment]
Fix is available on today's v1.20.6
