### ISSUE TITLE
Storage Full: Queue Crash

### ISSUE THREAD

**Issue by MrSwabe90** [avluis/Hentoid#131]
**Hentoid Version**: 1.2.1r2

**Device/Android Version**:Huawei P9 lite
Android 6.0 EMUI 4.1.1

**Issue details / Repro steps**: Crashes when going to Queue. / I have queued alot of doujins. Sorry i can't remember the quantity. But if i download another doujin it would start the download and finish it. The problem is that the queues can't be resumed because it crashes before seeing it.

**Stack trace / LogCat**:don't know where to find this sorry
```ruby
paste stack trace and/or log here
```

https://youtu.be/23JDja4u3SI
@AVnetWS/admin-team

**Comment by MrSwabe90** [comment]
Sorry. I discovered what's my problem. The storage used was full that's why it crashes. But thanks. Your app really help me in a strange way

**Comment by wightwulf1944** [comment]
Don't worry, we appreciate this bug report. Because now we know that having a full storage can crash Hentoid.

I apologize for the inconvenience. I was supposed to do a full storage test for this build but was too busy with work so we didn't find this bug.

Thanks for your efforts.

**Comment by avluis** [comment]
Thanks for this @MrSwabe90 😻

**Comment by nash14253** [comment]
hey i have the same problem... only my storage isn't full... the only reason i can think of is that i changed the downloads folder, i really wanna go back to downloading help pls

**Comment by avluis** [comment]
@nash14253 Please join our Discord server and send me a direct message -- I need more info to help you out.
