### ISSUE TITLE
My download button is lost (hentoid 1.3.10)

### ISSUE THREAD

**Issue by RDPMAN** [avluis/Hentoid#180]
I am using Hentoid 1.3.10.
When I tried to use Hitomi, the download buttons that I could see in the previous version were gone.
I deleted the cache and data, then reinstalled the Hentoid app, but the download button was still not visible.

My device is 'LG G2'.

**Comment by avluis** [comment]
More than likely because of this: #179

**Comment by Keikagura** [comment]
yeah.. its happen to me to..
i just can download on nhentai.net.. other sourche download button missing n some sourche keep failing when downloading to..

**Comment by avluis** [comment]
Since this issue is a result of #179 -- I'm closing this.
Please continue the conversation there.
