### ISSUE TITLE
"Delete all" feature [logicdefyer]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#205]
_From @RobbWatershed on June 12, 2018 19:15_

Add a button that would delete all books of the library

Location : settings (not toolbar), with double confirmation

_Copied from original issue: RobbWatershed/Hentoid#26_

**Comment by wightwulf1944** [comment]
I guess it's QOL improvement. Would a range selector or a select all function for Downloads screen suffice?

**Comment by RobbWatershed** [comment]
Range selector / select all wouldn't work for medium to large collections, since it would require tons of swiping through the collection to be sure everything is actually selected. Plus paged mode aficionados would have to do that page per page….

**Comment by RobbWatershed** [comment]
Abandoned in profit of #192 after talking with the OP
