### ISSUE TITLE
Built-in image viewer MVP

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#232]
#### Display

- [x]  Fullscreen buttonless mode
- [x]  Fit to screen
- [ ]  Fill screen -> #283
- [x]  Static zoom with Pinch or double-tap
- [ ]  Temp zoom when holding -> #284 
- [x]  Keep screen on

#### Browsing
- [x] Previous page / next page with swipe or touch regions
- [x]  Reading directions: Left to right, Right to left, ~~Vertical (Top to bottom),~~ Webtoon (Top to bottom continuous)
- [x]  Slider for fast browsing
- [x]  Skip to a specific page #
- [x]  Next/Previous page with the volume rocker
- [x]  Enable / disable Resume reading where the user last finished
- [x]  Super efficient forward caching to avoid delays while swiping

_______________

### NICE TO HAVEs (won't be developed in the 1st version; will need new issues to be created)

- Display thumbs when navigating with the fast browse slider -> #285
- Previous book / next book (using the downloads activity's ordering) -> #285
- Endless scroll (no page snapping) -> already done
- Bookmark an image -> #285
- Display the gallery (mosaic) and highlight bookmarks -> #285
- Slideshow mode -> #287
- Support for animated GIFs -> #286
- Manual image tagging -> #288
- Automated image tagging (see https://cloud.google.com/vision/) -> #288
- Search images by tags / smart books (books containing images based on their tags rather than their book ID)  -> #288
- Zoom width wise and height wise by clicking the corner of the page
- Random page sorting (rationale : users won't get bored when browsing picture galleries such as the ones e-hentai provides) -> #285

_______________

### Removed: 
- Fit to manga width (i.e. webtoon format where the image is narrow and very tall)
- Enable / disable auto screen rotation
- Horizontal and vertical browsing (see reading directions)

**Comment by wightwulf1944** [comment]
edited to add "- Keep screen on"

**Comment by wightwulf1944** [comment]
Edited:

Moved some to removed, added "Keep screen on" and Vertical reading mode in must haves

**Comment by RobbWatershed** [comment]
Added Option to resume reading where the user last finished [user V | br1vxv0t4bwa]

**Comment by RobbWatershed** [comment]
![orientation](https://user-images.githubusercontent.com/35880555/56341358-19b86300-61b5-11e9-9e96-d7a4d6427d32.png)

**Comment by RobbWatershed** [comment]
![viewer UI](https://user-images.githubusercontent.com/35880555/56341530-a5ca8a80-61b5-11e9-9acd-0cb6bd087507.png)

**Comment by RobbWatershed** [comment]
Reader integrated to Hentoid.

MVP features are done except :
- Fill screen : delayed because of a UX issue during page navigation
- Temp zoom while holding : too difficult to implement with our current architecture choice

Both will be re-created as separate feature issues.
