### ISSUE TITLE
This content cannot be downloaded. Sorry~

### ISSUE THREAD

**Issue by wfcntrl** [avluis/Hentoid#234]
Seems like nhentai changed something in the address. The site is throwing a 404 in tachiyomiEH too.

**Hentoid Version**:

**Device/Android Version**:

**Issue details / Repro steps**:

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by herdidi47** [comment]
have you already tried debug version at discord? there's already an experimental alternative parser there

**Comment by herdidi47** [comment]
they closed their API

**Comment by wfcntrl** [comment]
Thanks. I'm not in the discord yet. I'll try it once i get home.

**Comment by wfcntrl** [comment]
Closed since issue is already known.
