### ISSUE TITLE
Access by code [Alfred]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#240]
User searches a book ID (e.g 262285; numbers only; no letter) in the search bar :

- If the ID has any match (one or more) in the user's collection, the list of the matching books is displayed as search results
- If the ID has zero match in the user's collection, a dialog is displayed

		```
		ID not found - in which site would you like to search ?
		[hitomi]
		[nhentai]
		[pururin]
		[...]
		```

- If the user selects a site, the webview opens on the given book on the corresponding site

**Comment by wightwulf1944** [comment]
Just to explain the rationale behind this, on sites like reddit, directly linking to sites such as nhentai.net is prohibited. So what people do to share doujins is by sharing the Id instead. What people then do is manually type out the url "https://nhentai.net/g/" and then paste the id at the end.

The process is rather cumbersome so it would be nice if Hentoid provided a utility that would accept a snippet of text which would locate possible IDs and present a link to doujins which would open within the app.

I've only ever found IDs referring to nhentai pages

cite:
https://www.reddit.com/r/Animemes/comments/amlb7p/mystery_numbers/
https://www.reddit.com/r/Animemes/comments/araxb8/the_numbers_what_do_they_mean/
https://www.reddit.com/r/Animemes/comments/a59afy/war_of_numbers/
