### ISSUE TITLE
Option to change main screen background color [Paradoxikal]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#248]
the now brighter shade of red contrasts too much with the dark grey/black of nhentai, and it outlines the page. It's very distracting

The whole outline used to be the darker red that's at the top, which seemed to fit better
![screenshot_20190207-114856](https://user-images.githubusercontent.com/35880555/52525384-28f8cd00-2ca9-11e9-87cc-fedecca5e216.png)

**Comment by wightwulf1944** [comment]
I think the problem here is that the browser is in a floating dialog window

**Comment by RobbWatershed** [comment]
@wightwulf1944 do you mean we should change the way the browser is displayed ?

**Comment by wightwulf1944** [comment]
@RobbWatershed yes, a floating window should only be floating if it does not need the whole screen to display it's content. But here we have a floating window that's taking up as much space as possible.

Aside from that, I'd recommend tagging this as a `trival` level issue. If needed I can discuss the different issue levels on discord
