### ISSUE TITLE
Library screen : Display books grouped by [attribute] (e.g. grouped by artist) [xN0B13x, xyz777, Deadrate]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#254]
**User story**

I'd like to browse my collection in an organized way. Instead of having an endless stream of books, Hentoid should help me put them in groups / folders that I can organize myself.

Example 1 : I regularly transfer my newest downloads to my computer. I'd like to visualize books grouped by download date to be able to batch-archive them and to batch-delete them once they are transferred

Example 2 : I'd love to browse my collection with categories separated by artist to help me have a better view on all the books I own by a certain artist, be able to batch-archive and batch-delete them

**General specs**

1/ Browsing modes

The user can switch between several ways of viewing the collection that are called _browsing modes_

  - Flat mode (the current implementation)
  - Grouping by artist (books with multiple artists will appear in multiple groups)
  - Grouping by download date (see picture of grouping suggestion in the comments below)
  - Free grouping (user places everything manually)
  
"By artist" and "by download date" groups are generated automatically according to the books' metadata. The order of the books inside the group can be manually edited afterwards.

"Free grouping" is the only mode where
  - New groups can be added
  - Groups can be deleted
  - Groups can be reorganized
  - Books can be manually assigned to a given group or moved from one group to another

When a browsing mode other than "flat" is selected, a new UI panel is available to get a bird's eye view of all groups
 
  
2/ Features within a group

- Choose a cover as the group's "flag picture"
- Reorganize books order
- Delete all books
- Archive all books (generate as many ZIP files inside the device's default "Downloads" folder as there are books within the group)

In the picture viewer, "next book/previous book" controls should follow the order of the books inside the groups

**Comment by wightwulf1944** [comment]
Perhaps this can be fixed by implementing some sort of *grouping* mechanism in addition to sorting. The solution for this still needs to be discussed and drafted and as of the moment it is not a priority.

**Comment by RobbWatershed** [comment]
Will have to wait #322 as `FlexibleAdapter` has an actual grouping / header features

**Comment by RobbWatershed** [comment]
Also consider grouping manually (like virtual folders)

**Comment by RobbWatershed** [comment]
Might be possible with `FastAdapter` : https://github.com/mikepenz/FastAdapter

**Comment by RobbWatershed** [comment]
if there is a book story that spans multiple books i prefer to keep them in their separate folders, BUT together we a feature to group book in the library by artist it's interesting to consider a feature to manually group books together

this second grouping being only done in the apps memory and not changing the actual files

And it could allow reading all books of the group in one go

**Comment by RobbWatershed** [comment]
our main problem is that different from other normal manga reading apps we don't have a uniform thing to group books that would make sense aside from by author
what i mean by that is say there is a manga A all it's chapters can be grouped up together, but the same can't be done in our case since our chapters are submition and they vary a lot in how they are made example:
book 1 chapter 1 JP, book 1 chapter 1 EN
book 1 chapter 1  EN, book 1 chapter 1-2 EN
book 1 JP(complete book), book 1 EN(complete book)

**Comment by RobbWatershed** [comment]
Suggestion for age grouping
![unknown](https://user-images.githubusercontent.com/35880555/83323470-3ef41d80-a25f-11ea-9bc5-3161511c591f.png)

**Comment by RobbWatershed** [comment]
from user Deadrate

Something I would love to see for Hentoid is an "artist organized library", where you can see the artists name on the left side and their related works on the right side, and whichever book is your favorite you can pin it so that every time you scroll through the artist list and see the artist name you can easily identify them by the favorite book you pinned them with.

So basically, instead of a list for books as it is by default, it would be a list of artist names (left side) and their works (right side), you then click on the name and it opens their gallery containing all of their books just like the default list, but with an extra feature that allows the user to organize the order of the books manually, similar to the way I can do it when I'm changing the order in which books downloads first with the arrow icon.

I would like to see this because in my case I have about 2300+ books and I'm a neat freak when it comes to organizing my collection, but it's difficult to keep track of every book especially when they are "multiple part" works that sometimes a specific source has not released yet another may have the continuation of.

It's even worse when the artist has only one book and you really want to read it, but it's somewhere in the middle of the list and you can't remember the artist name or the tags related to it, and it becomes a "needle in the hay stack" issue.

=> To consider when writing specs for that feature

**Comment by RobbWatershed** [comment]
1. For books missing the artist name they automatically get placed in an "Other or N/A" section within the artist list, but if you as the user know which artist it belongs to then you can slap an "artist tag" on the book if it were to not have a name available which will send an "access" to the artist's collection that you tagged it to, thus making it look like as if it were always a part of that artist's collection. However, it will still be available in the "Other or N/A" section as a reminder that it was downloaded without an artist name. You never know if the sources re-uploaded the book and the user wants to delete the "no-name" book for the book that's been legitimately identified.

2. Regardless of source they still go to the same "artist collection", but are divided automatically by a colored line that separates the books from one source to another and above the books, the symbol of the source can be seen so that way the user can see where the book was downloaded. However, you can still organize the books manually to fit the order you wish it to be. Say you had a part 1 book from tsumino and part "n" from nhentai then you should be able to organize it manually so that you can organize it in the "appropriate" order you wish it to be while still giving you a visual cue that clearly indicates that book isn't the same source.

3. If the the user downloaded anthologies, or other books containing multiple artist name then the books will appear in all relative artist name, meaning if it were a ShindoL book plus any "x" artist, and you were to click the ShindoL's list you will see that multi-artist book and if you were to click the "x" artist name related to that same book you will still see that book in that "x" artist's collection because indeed both artists worked on it. This mechanic technically already exists in a way within Hentoid when you use advance searches with multiple artist names if you tagged them, so it's not impossible.
And this is another cool feature I think would be a "quality of life" improvement for such cultured adventurers who have multi artist books, allow the user within Hentoid to click on the artist name to be sent to that "x" artist's collection. You can think of it as a fast travel mechanic for when you are just reading a multi-artist book and suddenly your curiosity peaked and now you want to view that "x" artist's collection immediately, assuming you have at least 1 book pertaining to them.

**Comment by RobbWatershed** [comment]
Memo from previous notes

**User story** : Periodically, I tend to search for certain books I'm looking for that day. I scroll through rows of books which is either sorted alphabetically or by download date. Then if not I use advanced search to just narrow down the artist. But that also has its hurdles as some times its difficult to recall that artist's name, so I then search all the tags I can remember (including original website) and narrow down my choice that way.

Groups should also be selectable to select all contained books in one click (e.g. "delete all books from a given artist" / "delete all books older than x weeks")

**Suggestion**: Could you make it to were you can seperate your library based on artists? I know there is advanced search options, but the ability to do so would save on time searching. Plus, I can narrow down a book I want to find a bit faster.
