### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#263]
Migrate the app to AndroidX.

- [x] Main app
- [x] Fakku library

**Introduction**
https://medium.com/google-developer-experts/converting-your-android-app-to-jetpack-85aecfce34d3

**Good to know (especially AVOID maintaining simultaneously non-AndroidX and AndroidX branches because of the extra work any merge would require)**
https://blog.danlew.net/2018/11/14/the-reality-of-migrating-to-androidx/

**AndroidX-ready dependencies as of 2019/03/11**
https://github.com/AppIntro/AppIntro/releases
https://github.com/google/flexbox-layout

**Comment by wightwulf1944** [comment]
good citations on this issue

**Comment by RobbWatershed** [comment]
Done in d29113044fa4ad547c50e0c0f5b378384ada8c4f

**Comment by RobbWatershed** [comment]
Fakku lib needs to be migrated too
