### ISSUE TITLE
Filter/sort by books status (error / completed)

### ISSUE THREAD

**Issue by Azoz5643** [avluis/Hentoid#279]
that's not a big problem but i have 300 doujins downloaded i plan to read everytime i get bored but i found out that more than 60 doujins i downloaded had errors so i theres anyway the system can search for doujins that has errors like theres a page missing or any error just like the tag or languages filetering using the advanced search. that would be so much easier and very appretiated

**Hentoid Version**: 

**Device/Android Version**:

**Issue details / Repro steps**:

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by herdidi47** [comment]
hi. can you give more detail about filter that you mean? because hentoid can filter book base on tag, source, author, etc

**Comment by RobbWatershed** [comment]
Got it. I edited the issue because you initially typed your request in an invisible zone <.<

It has been added to the roadmap.

**Comment by herdidi47** [comment]
ha. nevermind me then :p

**Comment by Azoz5643** [comment]
i dont mean filtering i just made an example what i was asking for is just a way that can tell me if i have a book that is not downloaded correctly or missing a page or something like that

**Comment by RobbWatershed** [comment]
@Azoz5643 oh, in that case there's a button saying just that under every book
![error](https://user-images.githubusercontent.com/35880555/57572248-f3828d80-7417-11e9-8e3f-1050f208ea0b.png)

It only shows up when there's an actual error, and lead to a screen detailing what you (and us) need to know.
![errorPopup](https://user-images.githubusercontent.com/35880555/57572269-1ad95a80-7418-11e9-8eac-683dc3f2a551.png)

Does that answer your question ?

**Comment by RobbWatershed** [comment]
Closed, since the OP has not answered
