### ISSUE TITLE
Image Viewer : Slideshow mode

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#287]
**User story**
When reading a book, I need to have both my hands free (to drive, obviously <.<). Therefore, I need the app to turn the pages for me.

**General specs**
Tapping the "slideshow" button (action bar) starts the slideshow from current page. During slideshow no GUI element is visible - only the pages are displayed one after the other.

Interval between every page turn (seconds) can be changed by the user through the prefs menu [default : 2 seconds]

Transition style will be the same as regular browsing : page turn or transition off

Tapping anywhere on screen during slideshow mode cancels it.

Changing orientation during slideshow mode does not interrupt it.

**Comment by happyfilmmaker** [comment]
+1 for this feature. A setting for timer and transition style would also be important.
