### ISSUE TITLE
background support error

### ISSUE THREAD

**Issue by sir777** [avluis/Hentoid#290]
Background support error
Android 8.0.1 and LG X4.
An error occurs when I leave or drop the app with the Home button after adding an entry to the queue(hitomi)

004 - [Networking] : Timeout; HTTP statusCode=N/A; message=null @ https://aa.hitomi.la/galleries/1364691/04.jpg

**Comment by RobbWatershed** [comment]
Hello @sir777 
Thanks for the report !
Could you tell us which version of Hentoid you are using ?

**Comment by sir777** [comment]
@RobbWatershed
I using latest version.

**Comment by RobbWatershed** [comment]
The issue you reported is a network timeout. It means the Hitomi server was too busy when you tried to access it or too difficult to reach from where you were.

Unfortunately, we cannot do anything to solve that. Try to download again at another time, or using another connection.
