### ISSUE TITLE
Library screen : Grid view [avikbellic911, penca, Diskkk, LegendaryWitch, Krisbrine, Kenjie Himura]

### ISSUE THREAD

**Issue by avluis** [avluis/Hentoid#300]
From Reddit PM - user avikbellic911:

> I been using ur hentoid for quite a while, you have done a perfect job on it. As days pass my collections have piled up over 300+ downloads so scrolling is hard, is there a way u can introduce grid view? With grid view i think we can find the downloaded manga faster. Grid view including cover and name of the doujins.
Thanks again for the great app.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
See https://github.com/mikepenz/FastAdapter/issues/691
