### ISSUE TITLE
Filtering by pages

### ISSUE THREAD

**Issue by Azoz5643** [avluis/Hentoid#301]
**Hentoid Version**:Latest

**Device/Android Version**: 9

**Issue details / Repro steps**: Can you filter the downloaded doujins by pages as More/Less ? Sometimes I don't have much time and want to read something like less than 30 pages but searching for them makes a hard time. Thanks

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Duplicate of #222
