### ISSUE TITLE
Add to download queue by long click

### ISSUE THREAD

**Issue by messbuta** [avluis/Hentoid#319]
**Hentoid Version**: 1.7.6
**Device/Android Version**: lg v20
**Issue details / Repro steps**: long press manga and add to queue
i remember this function was in the app, but recently it does not work in hitomi.la
Did you guys delete in purpose or something unfortunate code pasta happened? :(

Anyway i am really feel thanksful to hentoid team. Keep it up!

**Comment by RobbWatershed** [comment]
Hi @messbuta and thanks for your feedback !

This issue has already been identified in #306 and will be added in future versions.

For the record, it was indeed removed 8 months ago because :
1/ It didn't work properly with all sources
2/ The feature was hidden, we thought nobody used it anymore
