### ISSUE TITLE
Queue screen - New design with two tabs (queue / issues)

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#323]
**User story**
I would like to make sure my collection has no missing pages before mass-transferring it to my PC. Any book with an ERROR status (i.e. missing pages) will thus have to be completed.

To do that, I need to quickly know which books have the ERROR status so that I can manually redownload the missing pages using the `(!)` button in the downloads screen.

**General design**
Modify the queue screen so that it gets two tabs (see https://material.io/components/tabs/)
1/ "Queue" = same as current screen
2/ "Issues" = list of all failed downloads that can be restarted

Restarting a failed download make it disappear from the "Issues" tab and adds it at the bottom of the queue, making it appear on the "Queue" tab

Visibility is defined like this
![queue2](https://user-images.githubusercontent.com/35880555/66746221-8e790b00-ee81-11e9-81b5-bda9a3410cd7.png)

**Comment by wightwulf1944** [comment]
I recommend putting this in the download queue screen

**Comment by RobbWatershed** [comment]
@wightwulf1944 I've written a user story for this feature. Can you elaborate on your recommendation ?
