### ISSUE TITLE
[1.8.1+ / AP19] Webview broken when viewing gallery pages

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#324]

**Comment by wightwulf1944** [comment]
Cannot reproduce using Sony Xperia 5c api 19

**Comment by RobbWatershed** [comment]
Issue reproduced by user GhostVirus on 4.4.2

**Comment by RobbWatershed** [comment]
Might be related to that : https://stackoverflow.com/questions/22288858/how-to-get-cookies-out-of-the-android-webkit-cookiemanager-on-a-non-io-thread

**Comment by RobbWatershed** [comment]
Fix prevents page from freezing but disables the use of cookies, which can have some side effects on sites with user accounts
