### ISSUE TITLE
Dark Mode Not "True" Dark Mode

### ISSUE THREAD

**Issue by blackziploc** [avluis/Hentoid#337]
The Dark Mode in the Viewer is not truly dark, could we please either have this option or it permanently be this way?

**Hentoid Version**: 1.8.3

**Device/Android Version**: Xiaomi 9T (K20) Android 9

**Issue details / Repro steps**: Enable Dark Mode, open, a book, realize it's not a true black. It's #121212 rather than #000000.

**Stack trace / LogCat**: None

![not dark](https://user-images.githubusercontent.com/36614608/61749190-25956180-ad70-11e9-8a17-750ea29ce472.png)
vs
![actually dark](https://user-images.githubusercontent.com/36614608/61749214-33e37d80-ad70-11e9-8db5-75bfcf467103.png)

**Comment by wightwulf1944** [comment]
The image viewer background is intentionally `#121212` to reduce contrast against images. At the moment there is no plan to have an OLED optimized theme.

**Comment by RobbWatershed** [comment]
New black theme makes the viewer background pitch black
