### ISSUE TITLE
Image Viewer - Add an option to enable bottom / top tapping while in vertical mode [Alfred]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#341]

**Comment by RobbWatershed** [comment]
When you are in horizontal view you can see the whole screen so you know what all that is being shown on that page and is confident that you can safely move to the next page.

Whether in vertical move that is not the case, unless you have already read a book once, you never know where is the end of a page and you are not sure if tapping to move to the next page will make you will a part of the previous picture making you need to manually drag back to see that.

There is also that, users sometimes on the rare occasions that the frames stack might also have an issue thinking they are clicking the end of page X to move to page X+1 but on reality they are already seeing the top of page X+1 and that makes a lot of problems to handle: do you go back to page X(since they clicked the top of page X+1) or do you move forward to show the full picture of page X+1 since the app was only showing a part of it.

**Comment by AlfredPaguio** [comment]
I see thanks for clarifying things
