### ISSUE TITLE
Image Viewer - Option to auto landscape/portrait when phone rotation is locked [dr_dsb]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#357]
Some users like to have orientation locked on their phones, but still need the viewer to adjust to portrait/landscape pictures without having to manually disengage orientation lock.

- Option 1 (if technically feasible) : Bypass orientation lock
- Option 2 : Detect and apply the most appropriate setting (portrait/landscape) according to picture dimensions

**Comment by RobbWatershed** [comment]
@wightwulf1944 do you know if option 1 (bypass screen orientation lock at app level) is technically feasible ?

**Comment by wightwulf1944** [comment]
Yup it's possible but the UX for this is a bit difficult to pull off so it must be a user preference that's off by default with labels that properly set expectation.

See [`android:screenOrientation` ](https://developer.android.com/guide/topics/manifest/activity-element#screen)
