### ISSUE TITLE
The word "group" returns multiple results when filtering the 'any' category

### ISSUE THREAD

**Issue by wightwulf1944** [avluis/Hentoid#362]
Reported from reddit: https://www.reddit.com/r/Hentoid/comments/cmbn34/bugbroken_please_fix/ew2zms7/?context=3

![4g6iunu64ne31](https://user-images.githubusercontent.com/2737347/62513816-dceda600-b84f-11e9-83d2-3b630c78db88.jpg)

**Comment by RobbWatershed** [comment]
O.o
Do they point to different books?
If so, is there a specific source for these books ?

**Comment by wightwulf1944** [comment]
Ah yes I did ask about that before trying it myself. It apparently leads to several books from several sources. I'm able to replicate the issue on my side as well. I've attached the reddit post of the bug report in the issue details above.

**Comment by wightwulf1944** [comment]
the chips that are shown in the 'any' category may be from different namespaces such that one `group` chip may be referring to an artist tag while another might be a generic tag. I'm wondering if using namespaces would fix this?

**Comment by RobbWatershed** [comment]
Using namespaces in the "any" filter would certainly clarify things, but given how many there are on the screenshot, I think there's an underlying bug

Plus it also displays elements without any books attached (see the blocks without any number on the bottom right), which is pointless when searching for books.

**Comment by RobbWatershed** [comment]
@wightwulf1944 To sum it up :
- Implement the following :
  - Display metadata (e.g. `artist:group`) when using the "Any" button
  - Don't display empty tags
- Send a fixed version to the OP and wait for a new screenshot to have a better look at what's going on

OK for you ?

**Comment by RobbWatershed** [comment]
One more area to investigate : nhentai books that have groups in them seem to all have a "group"attribute displayed under "Artist".

**Comment by RobbWatershed** [comment]
Link to v1.10.0-beta1 has been sent to the OP on Reddit

**Comment by RobbWatershed** [comment]
Feedback from the OP on Reddit
- The empty tags (with 0 matches) seem to have vanished
- "circle:group" is the effect of a bug with nhentai that has been fixed yesterday (any book with the "group" tag would also have "group" added to Artists/Circle automatically)

Now remains the issue of the nine isolated "tag:group"...

The OP has agreed to try a custom build
