### ISSUE TITLE
Image Viewer - Volume buttons to traverse pages stops working after navigating to another book

### ISSUE THREAD

**Issue by wightwulf1944** [avluis/Hentoid#363]
Affects 1.8.5 on some android 8 and above

Repro steps:
1. open any book
2. press volume up/down to confirm that it traverses to the next/previous page
3. tap the middle region once to show the hud
4. tap the next/previous book in the bottom bar
5. press volume up/down buttons

reported from reddit: https://www.reddit.com/r/Hentoid/comments/cmbn34/bugbroken_please_fix/ew15hfi/

**Comment by RobbWatershed** [comment]
I can't reproduce that on my end. 
@wightwulf1944 what Android version / flavour have you used to reproduce that ?

**Comment by wightwulf1944** [comment]
it occurs on some android 8 and above devices. This must be related to how android handles focus and key events. The key event listener is set on the recyclerview and touching anything else moves focus to that view. Whenever the recyclerview doesn't have focus the volume buttons stop working.

It might be better to move the key event listener to the root view of the fragment instead of the recyclerview. For testing we can contact testers that used to experience this similar issue before we added `requestFocus()`

**Comment by RobbWatershed** [comment]
Another user reports volume button stops working after using the bottom progress bar
 hentoid 1.9.1 and android 9 one ui 1.1
