### ISSUE TITLE
Image viewer - New setting for "Fling sensitivity"

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#364]
- Change "Fling sensivity" bar to a "Multi-page fling" switch
- Position "Off" = Position 0; Position "On" = Position 75
- Current setting : Any other value than 0 is migrated to "On"

**Comment by wightwulf1944** [comment]
What do you think of labeling it as "swipe to fling" instead? I think it's easier to imagine what it does with that name
