### ISSUE TITLE
"Hide from recent apps" option not working

### ISSUE THREAD

**Issue by morbitvs** [avluis/Hentoid#375]
**Hentoid Version**: 1.8.7 (136)

**Device/Android Version**: Moto G 2014 / 7.1.2

**Issue details**:
Marking the option **Hide from recent apps** in **Preferences** has no effect.

Hentoid shows the last screen you were seeing before going to recent apps list. For example:
If you were editing  **Preferences**, it shows in recent apps list:

![Screenshot_20190824-094003_teste](https://user-images.githubusercontent.com/54473797/63637615-915f3880-c654-11e9-98a5-8e41de84bc16.png)

 Something similar happens in case you were reading a manga. That problem was also present in 1.8.5, sorry for not reporting earlier and sorry for my weird english.

@AVnetWS/admin-team

**Comment by ArturRA** [comment]
Issue fixed with commit https://github.com/avluis/Hentoid/commit/cf6b51890b1fac3a6312b3a39b5cbbd38ef76e00
