### ISSUE TITLE
Blocked internet

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#380]
Im not sure hentoid can bypass blocked internet i mean some provider will not allow u for opening any porn website. It's happend to me but i also need VPN for downloading from Hentoid the app wont running if im not using vpn. Hope get answers very soon

**Comment by RobbWatershed** [comment]
Hentoid acts like a browser, using the connection provided by your device. 

We don't plan on integrating any embedded VPN feature in the app. 

If your ISP blocks art and culture sites, then you should use a VPN.

**Comment by Chocolalolz** [comment]
Hentoid ver: 1.8.7
Android/ Device ver: Sony Aqua M4/E2353
Issue: blocked from provider
