### ISSUE TITLE
Cant import manualy from pc

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#382]
Hentoid ver: latest
Android ver 6.0.1

Hey i found bug when i was downloading on pc then i paste the files on hentoid it doesn't read at all. Looks like when i restart hentoid i need to import the files i got 75 total but it's actually 24 (based on phone download)

**Comment by herdidi47** [comment]
hi. for importing from pc to hentoid, for hentoid to read the book, they need .json file that contain about the book information. without that it will not get read. usually .json file is generated when the download via hentoid started

**Comment by RobbWatershed** [comment]
If you're importing Fakku downloads, this app will help you generating Hentoid ContentV2 JSON files https://gitlab.com/zer02/FakkuDLs4Hentoid

If you're importing downloads from other sites, you'll have to find another solution to generate JSON files, or else the app won't be able to recognize your books.

**Comment by Chocolalolz** [comment]
i tried just copy paste it the json files but i cant be downloaded T_T

**Comment by RobbWatershed** [comment]
Could you elaborate on this ? I fear what you said is not detailed enough for us to help you...

**Comment by Chocolalolz** [comment]
Is like i downloaded 50doujin from PC but i have 25 on my phone so when i tried paste the doujin it was said "importing 75files" but the files doesn't import at all. I tried many times for it. I was trying copying the json file from doujin I've been download on my phone but it doesn't work 

Example: Asunama 3 > Copying the json file > paste it into comic 10 > try reimporting the doujin > doesn't work

**Comment by Chocolalolz** [comment]
I thought was it will be the same name Asunama 3 but the app doesn't make it double

**Comment by RobbWatershed** [comment]
Can you upload the import log?

It is located in your Hentoid folder. 

Thanks

**Comment by Chocolalolz** [comment]
[import_log.txt](https://github.com/avluis/Hentoid/files/3688612/import_log.txt)

**Comment by Chocolalolz** [comment]
is like impossible for me importing manually from PC but as i know i just need to edited the .json files but i need change it 1by1 gezz it's working but it takes so much effort for it

Example

i deleted original file Asunama_3 then i replace it with manual file i downloaded from pc it loads but it's only 17 pages (Asunama_3 has 17pages on it) but from pc got 673 files so i decided edited the .Json files 1by1 as the image name i copy paste it and it takes 15min just for that.

Yes it works if u editing it on pc but also it take to much time for it i prefer download from the apps lol

**Comment by Chocolalolz** [comment]
why still no reply after 4days? even i posted 11days ago

**Comment by herdidi47** [comment]
we all mostly active on discord. feel free to join us for faster response

**Comment by RobbWatershed** [comment]
> why still no reply after 4days? even i posted 11days ago

Pretty please. Last time I checked, you're neither my wife nor my boss. Remember the Hentoid team is doing this on their spare time.

That being said...

1. Thanks for the import log
2. It confirms that you do need to create a JSON file for each book. The app won't recognize them without the JSON.

What you're trying to do is very interesting, though. I'm creating another issue to add the feature you're looking for (auto-generate JSON files) in the app.
