### ISSUE TITLE
Auto-import folders without JSON files [Chocolalolz, Xiyo, Lugras, Azoz5643]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#387]
See #382 

__User story__
I have downloaded many art books using a 3rd party software, and I want to load them into Hentoid to have all my library in a single place.

Unfortunately, Hentoid only accepts to import books when they have a `ContentV2.json` file inside their folder.

Fakku books : I can use https://gitlab.com/zer02/FakkuDLs4Hentoid
Other sources : There's no other solution than manually editing a JSON file for every book I want to add to Hentoid. It takes a lot of time

~~__General spec (initial idea)__~~
Add a new option to the "refresh library" dialog. The option is "Auto-generate missing JSON files".
When activated, any detected subfolder with at least 1 image, but no JSON file will have its `ContentV2.json` generated by the app, and the book added to the library.

The name of the subfolder will be used as the book title, and add all detected pictures to the book, sorting them alphabetically according to their file name order.

~~Also consider auto-deflating imported ZIPs, CBRs and EPUBs.~~ -> Moved to #579 

__Detailed spec (new idea)__

_Import_
1. User selects a folder anywhere on the phone memory or SD card. This folder will become the "external library" folder
NB : We can't predict where the user will pick his folder, nor can we force him to choose a certain folder (that's now quite obvious with the experience of v1.12.0). The app will have to "discover" the folder tree to understand how to process it.
2. Explore the file tree from the selected location to find where books are located. Algorithm will be posted below once I'm satisfied with it. The goal is not to miss any book and to be smart enough to detect when chapters are used
3. Create a book entry for every detected book, filling title metadata and images (sorted by chapter and image file name)
4. Create the JSON file inside the book folder (when chapter subfolders are present, the JSON will be created in the parent folder where all chapter subfolders are located)

NB : Creating a JSON file is not completely necessary at this point, but it will be useful in the future when users are able to edit metadata

---

_Interaction_
- Deleting external book files (be it book or page) will be disabled by default. By principle, the original app should be the one doing it. An option will be available to enable that and will warn the user about the shortcomings (i.e. files are deleted but book might still exist in the original app)
- Redownload from scratch will be unavailable
- The "refresh library" launch dialog will change to include the location to refresh :
    - Hentoid library : Same as current behaviour
    - External library : Simple refresh of all external books without any renaming / cleaning option (once again, the original app is the one that should decide that)
- The "export metadata" and "import metadata" features won't interact with the external library

technically speaking, external books will be flagged with a specific EXTERNAL state to avoid processing them in the same "bag" as regular Hentoid books
apart from that, they will share the exact same structure in the database

**Comment by Chocolalolz** [comment]
i will correct u if u said there's no manually edited u'r not completly wrong atleast u still can add manually for this example

The doujin i downloaded was Asunama 3 so i've copied the original "Json files" then im adding manually with notepad

![image](https://user-images.githubusercontent.com/37593430/68292302-27d0c100-00be-11ea-94c9-c0deee7f2001.png)

**Comment by RobbWatershed** [comment]
**1. Find the actual library root**
1.1 Deep recursive search starting from the place the user has selected. We're stopping when we find at least 2 image files
1.2. Go up from this location and explore the parent folder
  - If the scanned folder contains subfolders whose names are ending with numbers, we're in a book with chapters => library root is up one level
  - Else we're in the library root

**2. Find books inside**
2.1 Start in the library root
2.2 Scan every subfolder
  - If the scanned folder contains subfolders whose names are ending with numbers, we're in a book with chapters => get pages from every subfolder and make it one single book
  - Else if the scanned folder contains images, we're in a book => get these images as pages and make it a book
  - Else we're probably in an artist or series folder containing books => remember the name of the subfodler as a generic tag and repeat step 2.2 on every subfolder (until max depth 3 to avoid losing our time scanning)
