### ISSUE TITLE
Hitomi can't open using Android Internet App.

### ISSUE THREAD

**Issue by pajake1224** [avluis/Hentoid#403]
Using Internet App, Hitomi can't connect with Hentoid App. It occurs error.(404 Not Found)

**Hentoid Version**: 1.9.3

**Device/Android Version**:Galaxy A8(2018) / Android Version 9 

**Issue details / Repro steps**: 

1. Access to Internet
2. Open any work
3. It will connect Hentoid App
4. Occurs '404 Not Found' error

**Stack trace / LogCat**: 404 Not Found
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
I can't reproduce it on my side.

Could you give us a book name, Id or screenshot? Thanks.

**Comment by pajake1224** [comment]
Also sometimes it doesn't connect with App

**Comment by RobbWatershed** [comment]
Search Hitomi books by launch code is also broken
