### ISSUE TITLE
Open source fakku.aar library?

### ISSUE THREAD

**Issue by Nonononoki** [avluis/Hentoid#418]
Currently the [library](https://github.com/avluis/Hentoid/blob/master/fakkuLib/fakku.aar) is a binary blob. Would it be possible to compile the source when building or provide the source?

**Comment by RobbWatershed** [comment]
The decoding algorithm for Fakku images is the product of retro-engineering from obfuscated code.

The library is intentionally separated from Hentoid and private only, and will be kept that way for caution. Fakku's algorithm is their property; making it public could be the source of many troubles.

Thanks for your understanding.

**Comment by Nonononoki** [comment]
Ah, thanks for the clarification :)
