### ISSUE TITLE
Networking error

### ISSUE THREAD

**Issue by pajake1224** [avluis/Hentoid#428]
I can't download from hetomi it get networking error

**Hentoid Version**: 1.10.1

**Device/Android Version**: Galaxy A8(2018) / 9

**Issue details / Repro steps**:  It occur networking error

**Stack trace / LogCat**: Networking error
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for the report. We're investigating this and hopefully release a fix in the following days.
