### ISSUE TITLE
Pages 4+ not appearing

### ISSUE THREAD

**Issue by XSonMan** [avluis/Hentoid#433]
V1.10.2
Upon sorting by random and after opening a doujin, pages 4+ after the currently opened doujin arent appearing.
i.e

Opened a doujin on page 8 after random sort
Doujins on pages 14++ aren't appearing

**Comment by XSonMan** [comment]
V1.10.2
Upon sorting by random and after opening a doujin, pages 4+ after the currently opened doujin arent appearing. 
i.e
1) Opened a doujin on page 8 after random sort
2) Doujins on pages 14++ aren't appearing

**Comment by Zeugma440** [comment]
Make sure you're using the latest version. This bug has been fixed in v1.10.2

**Comment by RobbWatershed** [comment]
Thanks for the report. So that bug hasn't disappeared yet..
