### ISSUE TITLE
Image Viewer - Max pages disappearing [Cat Knight]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#441]
the max number of pages dissappears after reading through some pages of a book

If you click to show the HUD and to hide it again it forces the max number of pagea to appear again, but that is a little annoying while reading

**Comment by ArturRA** [comment]
Update on how to reproduce the issue.
Open a book that will open in page 01.
Have the HUD hidden.
Move one page at a time till you reach page 10.
Result: The max number of pages will disappear.

**Comment by ArturRA** [comment]
The text is being properly displayed now, but it still shows the warning described in the commit link on my android 8.1. For now the issue is fixed, but i will create a new one with the warning from the link.
