### ISSUE TITLE
Image Loading/Rendering Loop

### ISSUE THREAD

**Issue by Compleur** [avluis/Hentoid#442]
**Hentoid Version**: 1.10.2

**Device/Android Version**: Huawei P20 Lite / 8.0.0

**Issue details / Repro steps**: Opening a downloaded album with the built-in image viewer puts it into (what I can only describe it as) an image loading/reset render loop. The only way to stop this (from what I've tried) is to close the application from the recent apps list or force closing the application. 

Extra notes:
- The archive is located on the SD card.
- The built-in viewer has worked in previous versions (1.9.4).

Expected behavior: Viewing an image from the downloaded album without flickering.

**Stack trace / LogCat**: n/a, only giving me a loop issue

[gfycat link to a relevant example clip](https://gfycat.com/hairyshadowydarwinsfox)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
First of all, thanks for the very thorough report!

It looks like your phone has memory issues with the viewer components. 

If it's a nhentai book I suppose the pics are jpg or PNG format. Could you try with a recent album from Hitomi (webp format) and tell me what happens?

**Comment by RobbWatershed** [comment]
According to our crash logs, it could be related to the upgrade we did from Glide v4. 9 to Glide v4.10. I'll investigate that.

**Comment by Compleur** [comment]
Reinstalled the latest update. The Hitomi source is giving me the same issue.

**Comment by RobbWatershed** [comment]
Alright, thanks for the feedback. It is definitely Glide v4.10 misbehaving. I'll switch back to Glide v4.9 for the next beta.

**Comment by RobbWatershed** [comment]
Edit : they just released Glide v4.11 with a couple bug fixes. Would you accept to test it on your phone?

**Comment by Compleur** [comment]
Sure. just let me know if there's extra installation that is needed.

**Comment by RobbWatershed** [comment]
Could you try this build on your phone : https://app.bitrise.io/artifact/28867998/p/604f98cdbf0d7de2ebed022fd933e547

It will safely replace v1.10.2. The only difference between the two is the version of Glide that is 1.11 instead of 1.10

* Crossing fingers *

**Comment by Compleur** [comment]
That seems to have fixed it!

**Comment by RobbWatershed** [comment]
That's fantastic !

=> I'll switch Glide to v4.11 for upcoming builds

Thanks again for your time and quick answers ;-)
