### ISSUE TITLE
E-hentai - Control which image resolution to download [-CarBoN-, Revrain]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#464]
The app has no fine control on what variant of the picture is downloaded. It just takes what's linked on screen. The "download original 900kb" link is not used

**Comment by RobbWatershed** [comment]
Available on today's v1.17.4-RC1 (Discord-only)
The release will be available publicly on 02/15

**Comment by EloidoV** [comment]
Not working at Opera Gx
