### ISSUE TITLE
requestLayout() being improperly called in android 8.1 related issue #441

### ISSUE THREAD

**Issue by ArturRA** [avluis/Hentoid#476]
Like described in issue #441 the text was fixed, but the logcat warning still remains i will attach a text file with the corresponding logcat.
[logcat.txt](https://github.com/avluis/Hentoid/files/4207889/logcat.txt)
.

**Comment by RobbWatershed** [comment]
Potentially useful : https://stackoverflow.com/questions/24598977/android-requestlayout-improperly-called
