### ISSUE TITLE
Random Sort By Error / Page Navigation 

### ISSUE THREAD

**Issue by XSonMan** [avluis/Hentoid#477]
Greetings,
Both errors are currently on build v 1.11.0

Issue 1 ( Random Sort Error )
A selected book that was sorted by random will make books from the next 2-3 pages ( depending on how many books you display per page ) disappear.
Screen recording for reproducing issue 1 ( google drive )
https://drive.google.com/open?id=1w2AAgMhVWH-KJocs57X39i9SuYZPY-3G

Issue 2 ( Page Navigation )
Sometimes it won't display the next page of downloaded doujins when you tap the next page arrow but will display the next 2 pages of the downloaded doujins. Sorting functionality has no effect on this issue. Sorry if it sounds vague.
Screen recording for reproducing issue 2 ( google drive )
https://drive.google.com/open?id=1Tefw58bZg5JR96sbBd9mRqjkQhKlEq13

**Comment by RobbWatershed** [comment]
Issue has been fixed. The fix will be published later this week in the upcoming hotfix release (v1.11.1)

**Comment by RobbWatershed** [comment]
Fixed in today's release
