### ISSUE TITLE
Random Sort ( Favourite / Delete ) not updating visually

### ISSUE THREAD

**Issue by XSonMan** [avluis/Hentoid#480]
Greetings,
Following issues occurred on v1.11.1

Issue 1 ( Hearts not updating upon tap when sorting randomly )
Upon tapping the heart/fav icon, it is not updated when sorting randomly but will act normally otherwise. Tapping the heart icon during random sort will not be updated visually but will register normally after setting to a different sort.
Screen caps for issue 1
https://drive.google.com/open?id=1GYgJlsyAS-DpaCRZsJtWbNT3HZHo3zjH
https://drive.google.com/open?id=1wjEahkE_dJ10QUfMHpV6ROS1Lr4pznr6

Issue 2 ( Books not visually removed when sorting randomly )
Issue 2 is related to Issue 1 in a sense that action made by the user is not visually updated but is registered. Occurs only in random sort.
Screen cap for issue 2
https://drive.google.com/open?id=1HocToAE5OjRTyezBBSNRc1uyBG_dn7-c

**Comment by RobbWatershed** [comment]
Refresh of the library screen was blocked when sorting was in random mode to avoid reshuffling the list when a new download appears.

That blocking has been removed to fix the issue. We yet have to find an easy way to prevent the reshuffling when items are added/removed to the list.
