### ISSUE TITLE
Download issue (NHentai)

### ISSUE THREAD

**Issue by XSonMan** [avluis/Hentoid#521]
Doujin from NHentai is not available to be downloaded possibly due to the new web layout

**Comment by RobbWatershed** [comment]
nhentai just said `Encountered some issues during migration. Site has been rolled back to old version for now, and will be upgraded after bugfixes shortly.`

I can't fix it until it reverts back to its new self...

**Comment by RobbWatershed** [comment]
`shortly` is now `in a week or so`. No comment

https://twitter.com/fuckmaou/status/1255323417596833793

**Comment by RobbWatershed** [comment]
Closing the issue for now. We'll be vigilant as soon as the new site pops up again.
