### ISSUE TITLE
Support to add books from external sources

### ISSUE THREAD

**Issue by Azoz5643** [avluis/Hentoid#522]
Hello, I have a lot of stuff ripped from Fakku in .zip formats, but I realized that Hentoid doesn't support that. 
I hope that we will be able to move the .zip (or any other format) to a specific folder inside .Hentoid
So we can view them normally, my suggestion for the folder to be called 'Local' or something like that, this would be a life changer. Thank you ^^

**Hentoid Version**: 1.11.4 (204)

**Device/Android Version**: 9.0

**Issue details / Repro steps**: Expected to work when adding a .zip .epub .cbz and the other famous book formats.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Hi and thanks for the feedback.

Support to import non-Hentoid books is coming in v1.12 : https://github.com/avluis/Hentoid/issues/387

Concerning Fakku, you can already use the excellent https://gitlab.com/zer02/FakkuDLs4Hentoid !
