### ISSUE TITLE
Library screen - View recent searches

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#526]
Display recent searches when using the library screen's search bar

![target](https://user-images.githubusercontent.com/35880555/81389138-a49a3180-9119-11ea-9abc-2ae726742426.png)

**Comment by BobbyWibowo** [comment]
+1. Also, while a general string-based history would be pretty good already, hopefully it will also later be extended with remembering the advanced toggles used during the past searches (e.g. included/excluded source(s) and all those advanced jazz)?

**Comment by RobbWatershed** [comment]
@BobbyWibowo turns out advanced searches were already stored in an URI. I included them as part of search history

**Comment by BobbyWibowo** [comment]
Lovely, many thanks!
