### ISSUE TITLE
Image Viewer - Lowered Quality

### ISSUE THREAD

**Issue by Chescaaa** [avluis/Hentoid#539]
**Hentoid Version**: 1.11.5

**Device/Android Version**:Vivo 1716, Android Version 8.1.0

**Issue details / Repro steps**:The quality of the downloaded images when viewed in the new hentoid image viewer is lower than its original quality. I've tried viewing the images using the default vivo image viewer and other image viewing apps and the quality is just fine. By the way, I'm currently using an older build of the app since the older image viewer works just fine.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Hi and thanks for the report.

Could you provide a book ID or URL we can check with ?
If Hitomi, please specify if you got the pictures in JPG or WEBP format.

Thanks !

**Comment by Chescaaa** [comment]
It's pretty noticable in this book https://hentainexus.com/view/5790

Thank you very much for your help!

**Comment by RobbWatershed** [comment]
I don't see anything suspicious on my phone.  It might be an issue with the default settings for hi-res image loading that might need to be fine-tuned.

1/ Could I ask you what is your device's screen resolution ?

2/ By any chance, are you seeing these kind of artifacts ? -> #358

3/ When zooming in, do you see a better image ?

Thanks in advance for your feedback.

**Comment by Chescaaa** [comment]
1. The screen resolution of my phone is 720x1440
2. I don't really see those in the images.
3. Zooming in actually lowers the quality even more.

+ I don't really know if this would help illustrate the issue better as I
can't really find the words to accurately describe it but when you compare
the old image viewer to the new image viewer, it would be just like
transitioning from 720p to 480p in a youtube video hahaha. It feels that
way to me.

++ I noticed just now that for this book https://nhentai.net/g/313045/, the
image looks just fine, however, when I checked other books, they still have
the same issue. Weird.

**Comment by Ketchup1138** [comment]
I got same problem too. Every problem Checaaa have I have too.

Hentoit Version: 1.11.5 (206)

Android Version: 7.0

Phone: Meizu

Marketing Name: M6T 

Model: M811H

**Comment by RobbWatershed** [comment]
@Ketchup1138 thanks for the feedback. For the record, your phone's screen resolution is exactly the same as Checaaa (720x1440).

**Comment by RobbWatershed** [comment]
Right, I can definitely reproduce it using 720x1440

![image](https://user-images.githubusercontent.com/35880555/81925058-44573400-95e0-11ea-938e-01579b6db08e.png)

I'll work on that and let you know.

**Comment by RobbWatershed** [comment]
Okay, there's a series of coincidences that lead to this issue :
- In order to fit book images to the screen, Android rescales them using a bilinear filter (the most simple one). That filter has proven to cause display artifacts, as seen in #358 
- Since v1.11.3, in order to avoid these artifacts, images that require to be rescaled significantly to fit screen are _resampled_ before being displayed. It's the case here when viewing this book (where raw image dimensions are 1360x1920) on a 720x1440 screen
- Since we can only resample by halving the size of the image, we end up with a _680x690 picture that has to be displayed zoomed in_. The specifics of the raw pictures of that book (that has all these little dots to create shades of grey), create display artifacts under these circumstances

**Comment by RobbWatershed** [comment]
Illustrating the issue with one of the "safest" pictures of the book - look at the black cloth while the screen zooms out

![539](https://user-images.githubusercontent.com/35880555/82033251-c311a700-969c-11ea-8815-f16ab2cd599f.gif)

**Comment by RobbWatershed** [comment]
Another user reports the same issue - 720x1440px / 269ppi

**Comment by RobbWatershed** [comment]
Fixed for next version (v1.12). A hotfix to v1.11 would be too complicated.

**Comment by RobbWatershed** [comment]
FYI, v1.12 should be release mid-june

**Comment by Chescaaa** [comment]
Thank you very much for the fix :)
