### ISSUE TITLE
Downloaded manga won't show up in library.

### ISSUE THREAD

**Issue by Jennitool** [avluis/Hentoid#549]
Happened twice when downloading from tsumino and nhentai (not sure about the other sites as these two are genwrally where i go usually go to). I have the manga downloaded in full and it even shows when you check the file via a file explorer but it won't show in the hentoid gallery.

Version 1.11.6 (211) 
*Happened to me once each on the 2 versi9ns prior to this one. Not sure which.

Huawei STK-22 ANDROID 9

**Comment by RobbWatershed** [comment]
Hi and thanks for the feedback !

I have a few questions :
- Could you upload the `contentV2.json` file located in one of these book's folder ?
- Does the books become visible after restating the app ?
- Does the books become visible after refreshing the library (prefs > storage > refresh) ?

**Comment by RobbWatershed** [comment]
No answer after 24 days; issue closed
