### ISSUE TITLE
Problem with Tags and Thumbnai with new Nhentai

### ISSUE THREAD

**Issue by Azoz5643** [avluis/Hentoid#558]
**Hentoid Version**:

**Device/Android Version**: Android 9.0

**Issue details / Repro steps**: Basically, nhentai did an update for their website, and tags now tell you how much content they have. 
As an example, Ahegao (1K) but after downloading you see the tag as ahegao1k and so on with all the tags (all downloads before the update have no problems, only new ones)
Also, there's n thumbnails with the new downloads, which works with all other source except nhentai for some reason.

**Stack trace / LogCat**: None
```ruby
paste stack trace and/or log here
```

 Hentoid doesn't allow screenshots for security reasons

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for the update. Will be fixed for tomorrow's release.

**Comment by RobbWatershed** [comment]
PS : You can enable screenshots in-app at any moment by using preferences > privacy menu.

**Comment by Azoz5643** [comment]
Ah thanks.. here's a screenshot if you still want it
https://files.catbox.moe/cz0f5r.jpg

The one below I downloaded 2 days ago, and the one on top it was in like 2 hours.

**Comment by RobbWatershed** [comment]
Fixed; will be published tomorrow
