### ISSUE TITLE
I can't import library

### ISSUE THREAD

**Issue by Ketchup1138** [avluis/Hentoid#564]
I couldn't open any hentai I download after update so I reintalled app but now I can't import my queue.

**Comment by RobbWatershed** [comment]
What do you mean by "I can't import my queue"?

**Comment by Ketchup1138** [comment]
Sorry I mean I can't import my JSON file. My queue list at inside it.

When I try import it at folders Hendroid not see it, don't let me click it.

**Comment by RobbWatershed** [comment]
If you mean the queue you have exported through the `preferences > storage > export metadata` menu, it has been exported into your device's regular downloads folder, not in the Hentoid folder.

Can you confirm you can find it there ?

**Comment by Ketchup1138** [comment]
I recorded a video https://youtu.be/48nro3sjmjU please look

**Comment by RobbWatershed** [comment]
Thanks for the vid, it's much clearer like this
Could you try that test build and tell me if it solves your issue ?

https://app.bitrise.io/artifact/41221465/p/33373105199148eb78b7e7a5c9a2cac9

**Comment by Ketchup1138** [comment]
Thank you very much! I thought I have to do everything with manually again. You made my day. Because of this I haven't done anything for a while now I feel fine.

**Comment by RobbWatershed** [comment]
So glad it worked for you !  The fix has been integrated for the next release :)
