### ISSUE TITLE
Image viewer - Images are really smooth

### ISSUE THREAD

**Issue by BlueDynamite** [avluis/Hentoid#565]
**Hentoid Version**: 1.12.0

**Device/Android Version**: Xiaomi Redmi 5 8.1.0

**Issue details / Repro steps**: The images are really smooth and text are harder to read when they are smaller. When zooming in they are even more blurrier.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for the feedback. That issue is being processed - see #556
