### ISSUE TITLE
The app doesn't support screenshots and recording

### ISSUE THREAD

**Issue by BlueDynamite** [avluis/Hentoid#566]
**Hentoid Version**: 1.12.0

**Device/Android Version**: Xiaomi Redmi 5 8.1.0

**Issue details / Repro steps**: The app won't allow me to screenshot it or record. If I record the app it all turns black. It also says couldn't capture screenshot when I take one.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Screenshots and videos are disabled by default for privacy reasons. You can enable them by checking the "App preview" option in Preferences > Privacy.
