### ISSUE TITLE
Can't find hentai2read source.

### ISSUE THREAD

**Issue by morbitvs** [avluis/Hentoid#567]
**Hentoid Version**: 1.12.0

**Device/Android Version**: Redmi 7A / Android 9 (MIUI 11.0.7)

I'm probably being stupid and I'm sorry for this, but I can't find hentai2read on Hentoid app.

Screenshots:

![image](https://user-images.githubusercontent.com/54473797/84543694-39242080-acd2-11ea-826f-14284d37419f.png)

![image](https://user-images.githubusercontent.com/54473797/84543648-1f82d900-acd2-11ea-9495-f7af1ed9cf52.png)

**Note**: Hentoid app wasn't finding any updates, even when using manual check, So I had to download 1.12.0 version and update Hentoid manually. When doing so the my library was reimported, but there were no other errors.

Thanks and sorry for my poor english.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for the feedback :)

Just use the "pencil" icon on top of the menu to access the menu editor. You'll see Hentai2read as an unchecked source. Just check it and you'll be fine !
