### ISSUE TITLE
Luscious.net - Visuals switch from mobile to desktop layout

### ISSUE THREAD

**Issue by Slowxzy** [avluis/Hentoid#568]
I dont why but **sometimes** it will be in the desktop mode

**Comment by RobbWatershed** [comment]
Hi and thanks for your feedback.

We can't fix that if we don't have a step-by-step way of reproducing that bug. Could you explain what we should do to trigger the bug ? And maybe provide a screenshot of what's wrong ? "being in desktop mode" is not very precise...

**Comment by Slowxzy** [comment]
I dont think it is a bug but it is very weird but it is different if you opened it from the browser

**Comment by Slowxzy** [comment]
![Screenshot_20200620-211743_Hentoid](https://user-images.githubusercontent.com/60755830/85208775-b3d8e580-b33b-11ea-9d09-bfd35681ac5b.jpg)
![Screenshot_20200620-211747_Hentoid](https://user-images.githubusercontent.com/60755830/85208779-b5a2a900-b33b-11ea-93af-222ec6638437.jpg)

**Comment by Slowxzy** [comment]
It says that the browser needs an update

**Comment by RobbWatershed** [comment]
@Slowxzy does that still happen with v1.13+ ?

There's been much work done in making sure the same agent is used throughout navigation.

**Comment by Slowxzy** [comment]
it doesn't happen anymore, but when you scroll up while you are on the filter screen (press on the hamburger button) the page will refresh
