### ISSUE TITLE
Display website title on the browser top bar

### ISSUE THREAD

**Issue by Slowxzy** [avluis/Hentoid#569]
Can u add the name of the website above cuz I am overwhelmed with the choices I have and forgot the names of the websites

**Comment by RobbWatershed** [comment]
Hi and thanks for your feedback.

Could you explain where that name should be added ? Just saying "above" doesn't help much....

**Comment by Slowxzy** [comment]
Mabey here
![Screenshot_20200620-210705_Hentoid](https://user-images.githubusercontent.com/60755830/85208571-41b3d100-b33a-11ea-88d8-ffe779b1d6e4.jpg)

**Comment by RobbWatershed** [comment]
Thanks for the feedback. Will do
