### ISSUE TITLE
Blank screen on exhentai

### ISSUE THREAD

**Issue by Slowxzy** [avluis/Hentoid#574]
it doesn't work

**Comment by RobbWatershed** [comment]
one-liners won't get you anywhere. Could you please explain what's going on ? Thanks

**Comment by Slowxzy** [comment]
I made an account and all but when I logged in it was just a white screen

**Comment by Slowxzy** [comment]
![Screenshot_20200620-212029_Hentoid](https://user-images.githubusercontent.com/60755830/85208812-f39fcd00-b33b-11ea-8038-5e2f5f6eb5e5.jpg)

**Comment by RobbWatershed** [comment]
Thanks for the feedback. We've been having issues reproducing this problem. I'll keep you informed when we make progress on that one.

**Comment by RobbWatershed** [comment]
Here's the link to the workaround : https://discordapp.com/channels/173995475098271746/185314059455823872/750611236181246032
