### ISSUE TITLE
Requests - Need this app on iOS

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [avluis/Hentoid#588]
Do you guys have a plan to made the iOS version? We need Hentoid for iOS ༼ つ ◕_◕ ༽

**Device/Android Version**:
iPhone XS Max, iOS 13.5.1

**Issue details / Repro steps**:
There is nothing yet.

One of the best app in the worlds!!
@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Heya and thanks for the kind words.

Hentoid isn't a company and cannot hire people / open an "iOS" branch by throwing money at the idea.
We're a tiny team of devs working in our spare time, and clearly focused on Android (very little skills in Apple SDK).

=> Any skilled iOS dev is welcome to join the team to build the iOS variant 📱 
We'll provide all the support we can to explain how the app works, including magnificient UML diagrams when needed 😁
