### ISSUE TITLE
NEED DELETE OPTION ON ERROR DOWNLOAD LIST

### ISSUE THREAD

**Issue by Frederic25** [avluis/Hentoid#590]
**Hentoid Version**:

**Device/Android Version**:

**Issue details / Repro steps**:

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Have you tried swiping the items, just like in the left tab of that same screen ? :-)
