### ISSUE TITLE
Library screen - Swipe to delete 

### ISSUE THREAD

**Issue by Slowxzy** [avluis/Hentoid#609]
can you readd the swipe to delete function in the library menu or just add a choice to be able to use this feature from the  interface & navigation settings

**Comment by RobbWatershed** [comment]
Sure thing. Glad to know there are people who actually appreciate that feature.

Now that the feature is less sensitive we can add it back.

**Comment by yul-oh895** [comment]
Thank you for this app.

Just adding my vote for adding this feature too. It was very useful to quickly delete books from the library and was disappointed it was removed previously. Hopefully we can use it again in one of the next releases.
