### ISSUE TITLE
Download issue. 

### ISSUE THREAD

**Issue by ExileTheAshes** [avluis/Hentoid#612]
Since the last update, I couldn't download anything. When I check the downloads they're in the "in progress" tab, but not started yet, when I hit resume download it immediately stops with a pop up "cannot download - no wifi" my device is connected the wifi. I've tried uninstall then re install Hentoid but still doesn't work. Is there something i should do? Or is this a bug?

**Comment by RobbWatershed** [comment]
Heya and thanks for the feedback

The wifi message is not labelled properly; what might happen is the queue detects your device is very low on storage space (< 2MB), which causes the queue to stop.

The message should read "Cannot download - Low on storage" instead of "Cannot download - No WiFi". This bug will be solved for the next release.

**Comment by ExileTheAshes** [comment]
![Screenshot_20200727_122810](https://user-images.githubusercontent.com/68844378/88520592-d3cb8b00-d004-11ea-8a97-f5c1fb356d5f.jpg)
Hello, thank you for replying, but I believe that I still have much space. So I don't think that's the issue.

**Comment by RobbWatershed** [comment]
Could you check what Hentoid says about it, in the `preferences > storage > memory usage` menu ?

**Comment by ExileTheAshes** [comment]
Oh. It says that I have 0% free out of 1.33 gb. How can I increase the memory used?

**Comment by RobbWatershed** [comment]
Are you sure the Hentoid folder is located on the SD card, and not on another volume ?

**Comment by ExileTheAshes** [comment]
Yes. Its located inside the downloads folder which is inside the SD card.

**Comment by ExileTheAshes** [comment]
I've managed to fix the issue by moving my downloads folder to outside the devices "downloads" folder.
Sorry for the inconvenience and thank you for your time.

**Comment by RobbWatershed** [comment]
You're very welcome
