### ISSUE TITLE
Favourite filter 

### ISSUE THREAD

**Issue by Slowxzy** [avluis/Hentoid#615]
Can you add a filter that shows the unfavourite hentai(s)

**Comment by RobbWatershed** [comment]
What you're asking will be done in #524 (favs overhaul)

**Comment by Slowxzy** [comment]
I think my case is a little bit different because I differentiate between the ones I read and one I didnt read by favouring them (the favourite ones = already read)

**Comment by RobbWatershed** [comment]
Did you know that there are features made to handle what you describe ?
- Unread books appear with a coloured bar at their right side
- In settings, you can adjust after how many pages a book can be marked as read
- You can also sort books by number of reads

With all that, I really wonder why you're using the favourite tag...

**Comment by Slowxzy** [comment]
Like I said I use the favourite tag to mark the hentai(s) I read but sometimes I skip ones and it is pretty hard to find it especially after reading some few pages of it (I have around 600 hentai downloaded)
