### ISSUE TITLE
NHentai Captcha

### ISSUE THREAD

**Issue by A-Vladimir** [avluis/Hentoid#621]
NHentai doesn't allow me to log in because it wants me to do the Captcha that it doesn't show.

**Comment by RobbWatershed** [comment]
Hi and thanks for the feedback.

Could you go to "About" and tell me what is the **Chrome version** displayed there (e.g. `Chrome v84`) ?

**Comment by A-Vladimir** [comment]
Chrome v84, and for some reason now it showed the captcha

**Comment by RobbWatershed** [comment]
I guess it's fine then 😁
