### ISSUE TITLE
Image viewer - Hold slideshow button to adjust the timer [A Microphone, Matapatapa]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#624]
Goal is to be able to adjust slideshow timer without going to the settings (books with more text require a longer timer)

Suggested solution : hold the "slideshow" action button to display a slider.
Instead of moving it across a fixed scale you just slide your finger left and right to increase or decrease the number

normal slider : pops up, you put your finger on it to instantly move where you want it
this one : you just hold, and slide your finger left and right and the slider disappears as soon as you let go

**Comment by RobbWatershed** [comment]
> normal slider : pops up, you put your finger on it to instantly move where you want it
> this one : you just hold, and slide your finger left and right and the slider disappears as soon as you let go

The Android framework doesn't allow that kind of interaction using a standard `MenuItem`. Allowing that would require to re-implement the top menu with another library, which is not worth doing right now imo.

**Comment by HyperPerplexion** [comment]
That is a wonderful idea and one even better than what I thought of. Thanks for trying to find a way and perhaps implementing it soon. :smile:
