### ISSUE TITLE
Can't Import JSON library file

### ISSUE THREAD

**Issue by Ketchup1138** [avluis/Hentoid#628]
I recorded here https://youtu.be/d4_GdbXkGXA 
-24  second video

-I got 50 book at library and 130+ queue

**Comment by RobbWatershed** [comment]
Please update your app. This issue has been solved.

**Comment by Ketchup1138** [comment]
App says "Update Check: No new updates."

**Comment by Ketchup1138** [comment]
![S00814-211113.jpg](https://user-images.githubusercontent.com/64573339/90279745-0df0b580-de6a-11ea-9436-a08a1acf9346.jpg)

Is this old version? Should I reinstall it?

**Comment by RobbWatershed** [comment]
This is the new version and definitely shouldn't behave like that. This is super odd

**Comment by Ketchup1138** [comment]
Do you want me to write something about my phone? I also did make a new JSON file and t app didn't see again.

**Comment by RobbWatershed** [comment]
It's okay, we'll take care about that for the next release.

**Comment by Ketchup1138** [comment]
You gaved me a link and fixed this problem. I tried again and still working. I will never buy a chinese phone. 

https://app.bitrise.io/artifact/41221465/p/33373105199148eb78b7e7a5c9a2cac9

**Comment by RobbWatershed** [comment]
Looks like I forgot to port the changes I did for this build on the main branch 😅 

Done now ! Sorry for the inconvenience...

**Comment by Ketchup1138** [comment]
You're human too 💜 thanks for fix
