### ISSUE TITLE
 Add "jump to page" for HentaiCafe

### ISSUE THREAD

**Issue by deliciouslytyped** [avluis/Hentoid#629]
I'm not sure if I missed something but it would be great if there could be some "jump to page" functionality on HentaiCafe, because currently I have to go back to where I was page by page and that really sucks.

Workaround in the meantime: browse to the page in firefox (e.g. by changing the page number in the url), and then use the "open with app" feature.

**Comment by RobbWatershed** [comment]
Is your goal to go back to the gallery page?

If so, just use the "gallery" navigation button (the one on the bottom bar, with the 6 little squares)

**Comment by deliciouslytyped** [comment]
Say I'm at page 123, I close the app. I open the app again. I am now at page 1. The only way I see to get back to page 123 is scroll to the bottom on every page and press the next number.

**Comment by RobbWatershed** [comment]
Okay, that's #461

**Comment by RobbWatershed** [comment]
Thanks for the clarification

**Comment by deliciouslytyped** [comment]
Ah, thanks! I didn't find that while searching for existing issues.
