### ISSUE TITLE
New field - Sort by Upload Date 

### ISSUE THREAD

**Issue by Ketchup1138** [avluis/Hentoid#637]
Can you add Sort by Release date?

**Comment by RobbWatershed** [comment]
Release date is unknown on all sites. Do you mean upload date?

**Comment by Ketchup1138** [comment]
Yes Upload date

**Comment by RobbWatershed** [comment]
Roger.
Keep in mind that this field is rarely parsed when downloading books. When we implement that feature, it will probably only work on newly downloaded books.

**Comment by Ketchup1138** [comment]
I don't mind downloading them again as long as I can sort them this way :D When I imported my list everything was collapsed everythings places is randomized so sorting by release date is only thing cameto my mind

**Comment by InFerNoBeasTz** [comment]
Can't wait for this. Needed this all my life. v1.16

**Comment by InFerNoBeasTz** [comment]
Hopefully this can get released earlier than v1.16

**Comment by RobbWatershed** [comment]
- [ ] PURURIN
- [ ] HITOMI
- [ ] NHENTAI
- [ ] TSUMINO
- [ ] HENTAICAFE
- [ ] ASMHENTAI
- [ ] EHENTAI
- [ ] MUSES
- [ ] DOUJINS
- [ ] LUSCIOUS
- [ ] EXHENTAI
- [ ] PORNCOMIX
- [ ] HBROWSE
- [ ] HENTAI2READ
- [ ] HENTAIFOX
- [ ] MRM
- [ ] MANHWA
- [ ] IMHENTAI
- [ ] TOONILY
- [ ] ALLPORNCOMIC
- [ ] PIXIV

**Comment by InFerNoBeasTz** [comment]
> * ~PURURIN~ not available
> * [x]  HITOMI
> * [x]  NHENTAI
> * [x]  TSUMINO
> * ~ASMHENTAI~ "X hours ago", "yesterday", "7 years ago" => not an actual date; won't use
> * [x]  EHENTAI
> * [x]  EXHENTAI
> * ~8MUSES~ not available
> * [x]  DOUJINS
> * [x]  LUSCIOUS
> * [x]  PORNCOMIX
> * ~HBROWSE~ not available
> * [ ]  HENTAI2READ
> * ~HENTAIFOX~ "X hours ago", "yesterday", "7 years ago" => not an actual date; won't use
> * [ ]  MRM
> * [ ]  MANHWAHENTAI
> * ~IMHENTAI~ not available
> * [ ]  TOONILY
> * [ ]  ALLPORNCOMIC
> * [x]  PIXIV
> * [ ]  MANHWA18

When is this feature getting released? Just saw that I replied to this a year ago 🤣

**Comment by RobbWatershed** [comment]
We're just following the roadmap. This one is currently under development as v1.16 has started.

**Comment by RobbWatershed** [comment]
Implemented in today's v1.16.1
