### ISSUE TITLE
External library numerical file name sorting

### ISSUE THREAD

**Issue by arjuna17jax** [avluis/Hentoid#654]
**1.12.7(257)**:

**Asus Zenfone Live L2/Android Oreo**:

**External library page sorting from file name messed up into 1,10,11,...,19,2,20,21,...,3,30,31,...**:

**No error message but it just an inconvenience**:
```ruby
paste stack trace and/or log here
```

![Screenshot_20201002-004012_1](https://user-images.githubusercontent.com/48570369/94844914-208a7280-0449-11eb-96b8-cbf6cc461b4f.jpg)
![Screenshot_20201002-004143_1](https://user-images.githubusercontent.com/48570369/94844945-28e2ad80-0449-11eb-8beb-60e0e0c111da.jpg)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for the feedback ! That's a good one that went under the radar during testing.

**Comment by arjuna17jax** [comment]
Thank you for for fixing it. I really need this. 👍
