### ISSUE TITLE
[ASK] Screen Shot on app

### ISSUE THREAD

**Issue by Chocolalolz** [avluis/Hentoid#672]
Is possible taking screenshot on app? I was trying and it doesn't work so i used video recorder to do screenshot

**Comment by FleetingComet** [comment]
![IMG_20201021_135339](https://user-images.githubusercontent.com/25319699/96678729-e146a600-13a4-11eb-9bd5-2d6e6505ce0f.jpg)

**Comment by RobbWatershed** [comment]
https://github.com/avluis/Hentoid/wiki/FAQ#FAQ3-8
