### ISSUE TITLE
[BUG] Download from Scratch does not fix/reset Nhentai Tags

### ISSUE THREAD

**Issue by anonymousUsers1** [avluis/Hentoid#675]
**Hentoid Version**:  1.12.9

**Device/Android Version**: Android 8

**Issue details / Repro steps**:  Downloaded comics a while back when the tag + n k glitch was happening (numbers appended to tag). I've tried redownloading relevant comics but the tags don't change and keep the issue unless I delete, search and add the comic again. This isn't really viable as there are quite a few comics with the issue.

**Stack trace / LogCat**:
```ruby
None
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
In truth, the current feature has a misleading label. It's actually "redownload pages from scratch", as it doesn't update the book's tags and only fetches the pages.

Anyway, it might be possible to do what you ask.

***

By the way :

> there are quite a few comics with the issue

`<rant>`
The fix has been made available in the 24 hours following the "tag +  n K" glitch. I guess people who continued to download in these conditions without the need for the update probably didn't care that much about it...
`</rant>`

**Comment by RobbWatershed** [comment]
Redownload from scratch now works as advertised and rescans all book metadata
