### ISSUE TITLE
Is this compatible with Bluestacks? Getting a "Cannot Download - Low Storage" error

### ISSUE THREAD

**Issue by Mentole** [avluis/Hentoid#676]
I am using it with Bluestacks and it works fine except I can't download anything because it gives me the "Cannot Download - Low Storage" error. Its probably has something to do with the folder selected to save. I just selected the folder I use to save my @voice files so I know Bluestacks will save there. Any solution?

**Comment by RobbWatershed** [comment]
Hentoid usually does that when selecting the device's download folder as it's own download folder. Could you try selecting another one?

You can see the memory report by going to preferences > storage > memory usage

**Comment by Mentole** [comment]
I was able to get them to download by changing the save folder to the downloads folder. Unfortunately it appears the only way to access the files is from the gallery section in Media Manager in Bluestacks.

**Comment by RobbWatershed** [comment]
App problem seems to be solved
