### ISSUE TITLE
No Fit Height option available for reader/viewer

### ISSUE THREAD

**Issue by kakarot28** [avluis/Hentoid#687]
I'm running the 1.12.9 version and it seems like there is no Fit Height option (without stretching) for the reader. This is extremely useful when trying to read in portrait mode because it uses all available screen space. I'd expect if the images are wider than the screen, the use will have to scroll a bit to see the rest of the image. Thanks

**Comment by RobbWatershed** [comment]
Looks like this was the intended behaviour of "fill screen". I'll see what I can do to fix that.

**Comment by RobbWatershed** [comment]
Well, that was quick. The fix will be available in upcoming v1.13. Stay tuned !
