### ISSUE TITLE
Mass Deletion Error

### ISSUE THREAD

**Issue by blackziploc** [avluis/Hentoid#692]
**Hentoid Version**: 1.13.0-beta3.1-DEBUG and 1.12.9

**Device/Android Version**: Samsung S20+ 5G Android 10 OneUI 2.5

**Issue details / Repro steps**: Select +70 books (+100 Always causes the issue). Books will start flashing and the notification will appear that the deletion has started, but you get an error code that the deletion has failed. Error code Ranges from 4xx to 5xxx depending on the number of books

**Stack trace / LogCat**: N/A

![Screenshot_4](https://user-images.githubusercontent.com/36614608/99443210-7ecfbf80-28e8-11eb-8f5a-a1857d4c8904.png)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Fixed for next release
