### ISSUE TITLE
App Crashing on Queue Screen

### ISSUE THREAD

**Issue by arjuna17jax** [avluis/Hentoid#700]
**1.13.0 (299)**:

**Infinix Smart 4**:

**App crashed when redownloading errors download from queue screen. Wether it by touching download button from individual book or touching redownload all from top right menu. The error downloads did moved to queue when restarting the app thought. And sometimes crash when opening queue menu after leaving the app in the background for a while**:

**Sorry I don't have access to PC**:

 
![Screenshot_20201125-195408](https://user-images.githubusercontent.com/48570369/100231432-926ace00-2f59-11eb-9d65-ce407288efa4.png)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
The issue has been identified and fixed. A patch will be released very soon. Thanks for your report.
