### ISSUE TITLE
New source : myhentaigallery 

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#705]

**Comment by RobbWatershed** [comment]
Possibly redundant with the other western comic sources - see how it hold against them

**Comment by RobbWatershed** [comment]
all books are present on hdporncomics, but their collection is missing some

**Comment by Flam3z** [comment]
Any reason this wasn't considered? As some users may also want to read regular porn comics as well from certain sites.

**Comment by RobbWatershed** [comment]
The reason has been stated : all books from myhentaigallery are present on hdporncomics, but their collection is missing some

=> **hdporncomics** has been suggested instead of myhentaigallery during the latest community vote
