### ISSUE TITLE
Won't slect download folder

### ISSUE THREAD

**Issue by Sapian16** [avluis/Hentoid#708]
Hentoid v1.13.4
I am using a Samsung Galaxy A10s and everytime I tap on the option to select a download folder the app crashes therefore I can't download plz help. Well I've tried the app a few months ago and waited for some new updates hoping it would be fix but....

**Comment by RobbWatershed** [comment]
Might be something on your side. Please check https://github.com/avluis/Hentoid/issues/670 for a possible solution

**Comment by RobbWatershed** [comment]
Stale issue
