### ISSUE TITLE
Cant open Tsumino in browser

### ISSUE THREAD

**Issue by XenTwo** [avluis/Hentoid#709]
![Screenshot_2020-12-21-01-21-06-579_me devsaki hentoid](https://user-images.githubusercontent.com/76405078/102721068-f8652e00-432a-11eb-9e72-a69d8c7e7257.jpg)

Hentoid 1.13.4
Im using Redmi 7, it never redirect me to the site

**Comment by RobbWatershed** [comment]
That was supposed to be fixed in v1.13.3

Could you try with augmented browser off (see settings > interface & navigation) ?

**Comment by XenTwo** [comment]
Oh it fixed, thanks
