### ISSUE TITLE
Can't download from Tsumino

### ISSUE THREAD

**Issue by zeroh025** [avluis/Hentoid#710]
**Hentoid Version**: 1.13.4 (311)
Chrome v50

**Device/Android Version**: happens in LG k5/android 5.1

**Issue details / Repro steps**: When I open any doujin on Tsumino, the download button on the bottom right of the app is greyed out and I can't click it. From other sites (tested Nhentai and Hitomi) it works normally.
I can open via web and the ones I already downloaded just fine, I just can't download new ones.

<!-- What is the error message that you got in the log? 
**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here -->
Here is a print of the issue
![](https://cdn.discordapp.com/attachments/489592720487350282/790716173263175690/Screenshot_2020-12-21-19-57-40.png)

And this is it as is normal on Nhentai

![](https://cdn.discordapp.com/attachments/489592720487350282/790716173015580682/Screenshot_2020-12-21-20-01-45.png)

<!-- Bonus points if you attach a relevant screenshot or a screen recording -->

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
I suggest you try :
- uninstalling and reinstalling the app
And/or
- settings > interface and navigation > uncheck augmented browser

**Comment by zeroh025** [comment]
I tried the augmented browser option even before and didn't work.
Tried reinstalling just now and it stays the same. 
Tried unchecking augmented browser again after reinstalation and still can't download.

**Comment by RobbWatershed** [comment]
I just realized you're using Chrome v50, which has a bug where sameSite cookies are not published by CookieManager.getCookie (see https://bugs.chromium.org/p/chromium/issues/detail?id=780491).

That causes issues that may prevent Hentoid from using secured sites such as Tsumino.

I'd advise you to update the version of Android you're using. On Android v5, afaik, there's no way to manually update the Chrome component apps are using.
