### ISSUE TITLE
Exhentai doesn't work

### ISSUE THREAD

**Issue by Hummidity** [avluis/Hentoid#720]
Whenever I click on exhentai a login page for ehentai forums pops up, whenever I try to login it shows the "logging in as(username)" screen then goes back to the login screen with an error saying "credentials invalid please try logging in again, if problem persists try using a different country or making a new account" not exact words btw. So I did try vpn, same problem, tried using different accounts, didn't work, tried making a new account, didn't work. Using the latest, v1. 13.5

**Comment by RobbWatershed** [comment]
Please try the tutorial on this link : https://e-hentaitagsearch.blogspot.com/2020/10/exhentai-blank-page-after-login-other.html?m=1

**Comment by RobbWatershed** [comment]
No feedback from the op
