### ISSUE TITLE
Suggestion and bug report.

### ISSUE THREAD

**Issue by Jinotu** [avluis/Hentoid#724]
Hey, I just wanted to say that now there are copies of each hentai source such as, 2 nhentai, 2 hentai2read and etc. Also I would like you to add these manhwa sources. That would be great. Manhwamanga.net , Manhwasmut.com , Manhwa18.com. Oh, and also please add an option to know if the hentai you are going to download is already downloaded. You know there are copies of each hentai and with different translators (and description), so if I already have in my phone, it warns me that I have something similar to it, if not the same. I hope you will really consider adding the sources above, if possible. Anyways, thanks.

**Comment by RobbWatershed** [comment]
Thanks for the report, altough I would've preferred something cleaner than this wall of text.

> now there are copies of each hentai source such as, 2 nhentai, 2 hentai2read and et

That's unusual. Can you try reinstalling the app ? 

>I would like you to add these manhwa sources. That would be great. Manhwamanga.net , Manhwasmut.com , Manhwa18.com

Added to the waiting list : https://github.com/avluis/Hentoid/issues?q=is%3Aissue+is%3Aopen+%22new+source%22

> Oh, and also please add an option to know if the hentai you are going to download is already downloaded. You know there are copies of each hentai and with different translators (and description), so if I already have in my phone, it warns me that I have something similar to it, if not the same. 

This is planned for next version (v1.14) -> https://github.com/avluis/Hentoid/issues/223

**Comment by Jinotu** [comment]
Okay, so now everything is back to normal. It did help. Can you add fingerprint option to security or at least make it 6 digital pin code. And how long it takes to add a new resource? And what do you mean "prefer something cleaner that this wall of text". Is there something more I need to include?

**Comment by RobbWatershed** [comment]
> Okay, so now everything is back to normal. It did help. 

Nice 😁 

>  Can you add fingerprint option to security

See #378

> at least make it 6 digital pin code

Why ? Unless your parents or roommates are pro hackers that know how to brute force your phone, I don't see the point.

> how long it takes to add a new source? 

Judging by the length of the current waiting list, that's months

> And what do you mean "prefer something cleaner that this wall of text". 

This page is a github issue. Its purpose it to describe and discuss **one single issue** (look at all the others, it's pretty clear).

A github issue is not a discussion forum either - kindly use Discord to ask questions and get answers from the devs and the community.

I'm closing the issue for now. If you have more concerns, please open one separate issue for each of them or join us on Discord. 

Thank you for your understanding.
