### ISSUE TITLE
App not updating itself

### ISSUE THREAD

**Issue by JarekDerp** [avluis/Hentoid#728]
**Hentoid Version**: 1.13.1
**Device/Android Version**: OnePlus 5T (OxygenOS 10.0.1)
**Issue details / Repro steps**: The app doesn't prompt me that there's a newer version nor does it update itself. A couple of updates ago you added a "Changelog" feature and that's the only place where it works and detects there's a newer version but when I click it to update, I can see (the bandwidth speed thing in notifications) that the phone is downloading something but then nothing happens again. Not a single time has the app updated itself since I started using it over a year ago.
**Stack trace / LogCat**: No prompts, no errors, nothing. The app just doesn't update at all.

I just updated the app so when I click "Manual Update Check", it does prompt me saying I'm using the latest version.
So the whole thing with connecting to the internet, downloading apk etc works but it doesn't trigger the apk install. I checked the settings and it has "Allow installing from this source" checked ok. So it should have access to install apks on my phone.

**Comment by RobbWatershed** [comment]
Thanks for the detailed report. We're well aware of that and are trying to find a solution for the devices where it doesn't work.

In the meantime, you can manually update by downloading and installting the latest APK on Github or Discord.

**Comment by JarekDerp** [comment]
Oh, ok. I couldn't find it on here so I reported it.
I also use "AnYme X" and "Tachiyomi" (both from git) and AnYme also doesn't update itself on my phone. Tachiyomi on the other hand probably sort this problem out as a couple of months ago the app started updating itself just fine.
https://github.com/tachiyomiorg/tachiyomi
They share source code so maybe you can peek at their solution to the problem?
Thanks for the brilliant app by the way :) Keep up the good work 👍

**Comment by RobbWatershed** [comment]
Thanks for the suggestion. As a matter of fact, we already did that check and saw that Tachi still uses the technically deprecated way of auto-installing. We switched from that to the new recommended way for v1.13. However, that new method doesn't seem to work on all devices. That's the magic of Android for you.... 😁

**Comment by RobbWatershed** [comment]
Fixed during v1.15 development

**Comment by JarekDerp** [comment]
Actually, I think this might have been my fault. I like to disable notifications from all types of apps as I don't like seeing them and I did the same with this app.
The app was downloading the update but you have to click it in the notification to trigger the installation... I assumed that once the update is downloaded it will prompt me to install without me pressing anything in the notification bar.
