### ISSUE TITLE
Can't download a particular chapter from fakku

### ISSUE THREAD

**Issue by Knobibrot** [avluis/Hentoid#736]
**Hentoid Version**: 1.13.8

**Device/Android Version**: Samsung Galaxy A20e/A202FXXU3BTK2

**Issue details / Repro steps**:
There is this one chapter on Fakku that I cannot download with hentoid because the button on the bottom right is greyed out.
I can read the chapter without problems and downloads work for every other chapter that I've tried.

[screenshot of what it looks like](https://imgur.com/a/ExLiO7R) NSFW, obviously

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Hi and thanks for the report.

Looks like this book's URL is formatted in an unexpected way.

This will be fixed for the next release

**Comment by Knobibrot** [comment]
"Welcome!" from Hamao has the same issue (greyed out dl button). I'm writing this in case the formatting for this chapter is different from the other one or it's some other independent problem.

**Comment by RobbWatershed** [comment]
Fixed in today's v1.13.9
