### ISSUE TITLE
Cannot download from fakku anymore

### ISSUE THREAD

**Issue by Knobibrot** [avluis/Hentoid#739]
**Hentoid Version**: 1.13.8

**Device/Android Version**: Samsung Galaxy A20e/A202FXXU3BTK2

**Issue details / Repro steps**:

Any chapter that I try to download currently appears in the errors tab with every page missing. I tried to download a chapter from nexus for testing and that worked without a hitch.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Care to share an error log ?

**Comment by Knobibrot** [comment]
Ah yes, of course. I didn't realize that there was a log. orz
"Total images in download: -1
Images without error: -1
Images with error 0
First error: No account or insufficient credentials - Your Fakku account does not allow to download the book Helping Hand. Your have to be logged with a paid Fakku account to download non-free books. Download aborted."
I actually got logged out in the hentoid fakku tab and didn't realize! However, even after logging in I cannot download the chapters. I am a subscriber and I can read them in the tab, only the download does not work.

This is not important but, but I also noticed some language mistakes in the error log. "Your have to be logged" should be "You have to be logged in".

**Comment by Knobibrot** [comment]
Update: If I delete the download from the errors tab, then I can start the download again from the fakku page and will go through this time. But when I restart the download from the errors tab, it will fail again.

**Comment by RobbWatershed** [comment]
> If I delete the download from the errors tab, then I can start the download again from the fakku page and it will go through this time. But when I restart the download from the errors tab, it will fail again.

Yup, redownload from scratch cannot fix authentication problems. You've found the workaround. Can this issue be closed ?

**Comment by Knobibrot** [comment]
> Yup, redownload from scratch cannot fix authentication problems. You've found the workaround. Can this issue be closed ?
From my point of view, sure. All my problems are solved. I didn't close the issue myself because I didn't know if this was intended behavior. Closing now.
