### ISSUE TITLE
Add Torrent Download for EHentai and ExHentai

### ISSUE THREAD

**Issue by sydneybright** [avluis/Hentoid#743]
Asking for the user to be able to download torrents from Ehentai and Exhentai

Current version: v 1.13.9

**Comment by RobbWatershed** [comment]
That should already be the case (see #500)

When clicking a torrent link, Hentoid should ask you which app you want to open the torrent with.

We've successfuly tested it with uTorrent.

**Comment by RobbWatershed** [comment]
Two weeks without a single answer - let's consider the problem solved.

If that's not the case, please reopen it and explain

**Comment by Sin-Shadow-Fox** [comment]
@RobbWatershed I know I'm kind of hijacking this thread but it doesn't look likes it's being used, and my issue is tangentially related. I've just uploaded my first contribution to e-hentai and i want to add a torrent to it but i have NO idea how to do that. I've downloaded hundreds of torrent/magnets but I've never made one myself and i don't know if e-hentai has an automatic process for that or not.

**Comment by RobbWatershed** [comment]
@Sin-Shadow-Fox you are indeed hijacking an issue closed 3 years ago, which explains why it isn't "used"

The Hentoid GitHub is a place to discuss the Hentoid app, not how to use site X.

You may have a better chance at getting help by dropping by our Discord and ask your question in #general.

**Comment by Sin-Shadow-Fox** [comment]
> @Sin-Shadow-Fox you are indeed hijacking an issue closed 3 years ago, which explains why it isn't "used"

Right, so it's perfect.

> The Hentoid GitHub is a place to discuss the Hentoid app, not how to use site X.

Well the thread say's "Add Torrent Download for EHentai and ExHentai" not "Add Torrent Download for Hentoid and X (formerly twitter)"

> You may have a better chance at getting help by dropping by our Discord and ask your question in #general.

I'm trying to cut down on joining too many discord servers, they're ruining my sleep. I miss good old fashioned forums, no commitments, no subscriptions, just come ask your question and leave. Those where the good old days.

**Comment by RobbWatershed** [comment]
> I'm trying to cut down on joining too many discord servers, they're ruining my sleep. I miss good old fashioned forums, no commitments, no subscriptions, just come ask your question and leave. Those where the good old days.

You're so right about how forums were simple, friendly and efficient, no doubt about that, man 👍 

You know you can mute Discord servers, and also leave them once you got your answer, right? If I left all notifications on I'd be in a constant state of mental breakdown.

**Comment by Sin-Shadow-Fox** [comment]
"Constant state of mental breakdown" Yep that sounds about right XD

And as for why i don't "mute/leave"? Well i guess i can only blame my autism for that. Even when i mute servers i still see that red notification symbol and it gets to me and i feel bad for joining a server just to ask a question and then leaving, like I'm just using them. I know it's in my head, i know it's not a real issue with discord but i can't help it.
