### ISSUE TITLE
Download errors in hentainexus

### ISSUE THREAD

**Issue by Jinotu** [avluis/Hentoid#746]
2 errors
2021-02-05T12:09:45.473 01 - [Networking] : Server error; HTTP statusCode=504; message=null
The number of downloaded images (49) does not match the book's number of pages (50) @ https://hentainexus.com/view/2816
Error log : end
And this happens with other hentais as well, not only this.

**Comment by RobbWatershed** [comment]
Seems to be fixed - will be available on next update
