### ISSUE TITLE
Fakku: Insufficient credentials errors

### ISSUE THREAD

**Issue by Knobibrot** [avluis/Hentoid#756]
**Hentoid Version**: 1.14.1, but this problem was already there before I updated.

**Device/Android Version**: Samsung Galaxy A20e / Android Version 10

**Issue details / Repro steps**: Whenever I try to download any chapter from Fakku, I get the insufficient credentials error. But I am logged in with an account that has a subscription. When I log in with this account on desktop, I am able to read whatever.
Deleting the download from the queue and redownloading does nothing.
When I try to read any chapter in the app, it shows 00/00 pages.
I also updated hentoid to the newest version but the behavior before and after the update was the same.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
FAKKU strengthened their security measures to prevent Hentoid from downloading their books, including legitimate users.

We're under discussion with them to restore this feature

**Comment by Knobibrot** [comment]
Any update on how the discussion is going?
