### ISSUE TITLE
Suggestion on how manhwa should look like

### ISSUE THREAD

**Issue by Jinotu** [avluis/Hentoid#759]
Hi, I just want to suggest that you change the way manhwa looks from toonily or any other site similar to it. It's just that manhwa is very long and the app is just dividing it into pages like hentai manga. Can you please make it look like the same as on site toonily, please? Like here.
![Screenshot_20210311-231855_Hentoid](https://user-images.githubusercontent.com/77118844/110891723-93cdc580-82c0-11eb-8e70-82e814c74e23.png)
Cause as of now it looks like this.
![Screenshot_20210311-230956_Hentoid](https://user-images.githubusercontent.com/77118844/110891545-35a0e280-82c0-11eb-91f2-676910d117dd.png)
It's short. I need one full chapter like on the site. Also you see the blank space on both sides, right?! You need to get rid of it as well.

**Comment by RobbWatershed** [comment]
Hi and thanks for your feedback !

In the viewer, have you tried using top menu > ... > Book settings > Browse mode > Top to bottom ?

That mode has been designed specifically for manwha 😉

**Comment by Jinotu** [comment]
> Hi and thanks for your feedback !
> 
> In the viewer, have you tried using top menu > ... > Book settings > Browse mode > Top to bottom ?
> 
> That mode has been designed specifically for manwha 😉 

Oh, okay I did try one mode and that's all. Didn't try everything there is. But can it be done only to manhwa only and not other manga, because everything becomes like that.

**Comment by RobbWatershed** [comment]
Sure, you can keep horizontal mode on global default settings and set top to bottom mode for manwha books individually, using the book settings. The app will remember these books have to use the mode you set.
