### ISSUE TITLE
App keeps crashing when I start it

### ISSUE THREAD

**Issue by MTNdew2** [avluis/Hentoid#768]
I don't have much info to give here, other than it keeps crashing for some reason

**Comment by Draakvoid** [comment]
If you have a Samsung s10 and recently updated your os . It is a new known issue with alot of apps and you need to go into settings.  Storage. Apps. Android webview. Click the three dots and Uninstall updates

**Comment by RobbWatershed** [comment]
More info here : https://www.reddit.com/r/Hentoid/comments/mb0xtt/app_keeps_closing/

**Comment by RobbWatershed** [comment]
For people who had problems with WebView version 89.0.4389.90 google has resolved the issue in version 89.0.4389.105 so you need to update your app right away!

quoted from google:
“We have resolved the issue with WebView that caused some apps on Android to crash for some users. Updating Android System WebView and Google Chrome via Google Play should now resolve the issue”
