### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by Jinotu** [avluis/Hentoid#780]
Please add an option to find hentai with writing where it was downloaded from, such as nhentai and etc. So is easier to filter them even if you don't know the name of a certain title but know the source where it was downloaded. And please update milestone regularly so I can see if you are close to releasing a new update as I always look forward to it.

**Comment by RobbWatershed** [comment]
![image](https://user-images.githubusercontent.com/35880555/113481316-21a06900-9499-11eb-983f-c590d2f8e42d.png)

**Comment by RobbWatershed** [comment]
> Please add an option to find hentai with writing where it was downloaded from, such as nhentai and etc. So is easier to filter them even if you don't know the name of a certain title but know the source where it was downloaded.

Right now, every downloaded book is displayed with the icon of its source, plus advanced search can filter by source. Is there something missing ?


> And please update milestone regularly so I can see if you are solving the problem as I always look forward to updates.
The project page (https://github.com/avluis/Hentoid/projects/2) is updated live as development progresses. If you want detailed news, exclusive content and memes, you're welcome to join our Discord server 😁

**Comment by Jinotu** [comment]
> > Please add an option to find hentai with writing where it was downloaded from, such as nhentai and etc. So is easier to filter them even if you don't know the name of a certain title but know the source where it was downloaded.
> 
> Right now, every downloaded book is displayed with the icon of its source, plus advanced search can filter by source. Is there something missing ?
> 
How can I filter so only the titles from nhentai gets displayed then?

**Comment by RobbWatershed** [comment]
tap on search bar > tap "advanced search"

Source filter _and_ multitag search are available

**Comment by Jinotu** [comment]
> tap on search bar > tap "advanced search"
> 
> Source filter _and_ multitag search are available

My goodness, so obvious and yet didn't notice. Thank you for pointing that out.
