### ISSUE TITLE
Extension request : hentaimimi

### ISSUE THREAD

**Issue by aofukai7** [avluis/Hentoid#789]
![Screenshot_2021-04-29-06-03-18-49](https://user-images.githubusercontent.com/64181165/116483259-f00c9900-a8b0-11eb-966a-269da6a6c27f.jpg)

Source : https://hentaimimi.com/

**Comment by RobbWatershed** [comment]
Unfortunately, we cannot support a site that hosts FAKKU material if we want to keep support for the real FAKKU site.
