### ISSUE TITLE
Request for a new feature

### ISSUE THREAD

**Issue by Jinotu** [avluis/Hentoid#792]
Version 1.14.4

I would like to request to add a feature, if you can call it so, just to be able to favorite all titles of specific source all at once. Using advanced search to filter from what source the titles need to be favorited. For example to favorite all titles from Hitomi or any other source you want to favorite and delete not favorited through settings. Also add opposite of it, unfavorite all titles all at once if you to totally erase everything. 

 I might be the only one asking of this, but I hope you add it, even if per request of one person. 

Oh, and everytime I refresh library, some pages of some titles disappear and I need to download the missing pages again. There is an icon for such case, a download button with plus any number above it. Should I just open another issue on it?

**Comment by RobbWatershed** [comment]
> I would like to request to add a feature, if you can call it so, just to be able to favorite all titles of specific source all at once. Using advanced search to filter from what source the titles need to be favorited. For example to favorite all titles from Hitomi or any other source you want to favorite and delete not favorited through settings. Also add opposite of it, unfavorite all titles all at once if you to totally erase everything.

As discussed on Discord, the upcoming v1.15 will feature a "select all" command that will allow you to mass-delete books without having to use "favourites" + "delete everything except favourites"

**Comment by RobbWatershed** [comment]
> everytime I refresh library, some pages of some titles disappear and I need to download the missing pages again
next time it happens, could you please check the folder of one of those books to confirm the image files are gone for real ?
