### ISSUE TITLE
New source : uncensoredmanga.com

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#806]

**Comment by blackziploc** [comment]
Note: URL Update to mangasincensura.com

Captcha hiding each chapter as well, no issues after navigating to Chapter URL

**Comment by RobbWatershed** [comment]
These popup-infested captcha pages, and the fact that they've been positioned for each and every chapter, is downright cancerous.

I'll do some more tests, but I'm not sure this site is fit to be supported here.

**Comment by RobbWatershed** [comment]
I can't even get a correct display of that captcha on the Hentoid browser. The only thing that appears clearly is that "click here continue" button that leads to a scam page

=> abandoned
