### ISSUE TITLE
Issue: App stutters, crashes and freezes with extremely large libraries, especially in advanced search.

### ISSUE THREAD

**Issue by Gitnon12** [avluis/Hentoid#810]
A bit embarrassing but I just wanted to report this issue. Probably low priority as I can't imagine most people download enough for this to be a major issue.

**Hentoid Version**: v1.14.10 - although issues have occurred with older versions too, usually the most up to date version across the past month or three.

**Device/Android Version**: Snapdragon 845 ,6GB RAM, Android 9/10

**Issue details / Repro steps**:  When handling extremely large libraries of 15,000+ entries or 3-400+GB the app begins to suffer from several errors:

- Tags in advanced search are slow to load and can 'hang' freezing the app and requiring the app to be 'force closed' through the settings
- Subsequently opening the app and going into advanced search will result in another crash if you do not wait at least 15-30 seconds 
- After selecting 1 tag in advanced search, you need to wait 10-30 seconds before searching for another, or it can eventually get stuck looking for available tags after 3-6 tags and require a hard restart.
- Scrolling up and down the library slowly will result in temporary .5-2 second stutters or freezes
- Selecting a comic for deletion results in it instantly acting as if you selected then deselected it. To properly select it you must press down as if to select then scroll up or down before it detects your selection. I think it's something to do with the long press action.
- Reinstalling the app and restoring the library results in significant improvements to the tag issues - although they still exist and are significant.

**Stack trace / LogCat**: No error log, just freezes and crashes

Also curious but could too low RAM have anything to do with this? 

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for your feedback. That part of the app hasn't been reviewed or optimized for quite some time, and could indeed do with some cleanup. We'll try and embark that in the v1.15 backlog.

**Comment by RobbWatershed** [comment]
@Gitnon12 Could you please test with the attached build where I made a few adjustments ?

<https://app.bitrise.io/artifact/101114365/p/002c2b2c362115073322b1bc651063f9>

Please report : 
- If advanced search is faster by default
- If unchecking `Settings > Interface & Navigation > Count available books` helps speeding up advanced search

NB : Attached build is equivalent to v1.15.14 with a few experimental fixes

**Comment by RobbWatershed** [comment]
No feedback from the OP after more than 30 days -> issue closed

Upcoming v1.15.15 will feature fix attempts developed to answer that issue. Join our Discord to download it or wait until January the 5th.
