### ISSUE TITLE
Issue: Upon reimporting library from downloaded files, app does not import metadata from the contentV2.json file

### ISSUE THREAD

**Issue by Gitnon12** [avluis/Hentoid#812]
**Hentoid Version**: Hentoid v1.14.10

**Device/Android Version**: Snapdragon 855 / Android 11

**Issue details / Repro steps**:

- Copy library from sd card of original phone into internal memory of new phone
- Install Hentoid
- Set directory to the .hentoid directory and let it import files
- Wait for app to import the library
- Notice most comics are missing all tags not directly in the heading and say [no data]

Attempting to import an export JSON file results in a majority of entries showing up in the issues tab in queue as items for which the folder could not be found.

Clicking the nhentai link in the library leads to an error page caused by going to nhentai without the specific code/url.

Misc details: Library is very large and files can be opened in other apps without issue to verify JSON data is complete.
Misc details 2: Some entries successfully import data, but a majority do not

**Comment by RobbWatershed** [comment]
Thanks for your feedback.

The app generates a log whenever it imports libraries. You can view the log in tools > app logs

If that doesn't answer your question, I invite you to contact me on the Hentoid Discord. We'll sort that out by DM.

**Comment by RobbWatershed** [comment]
No feedback from the OP for one entire month. Issue closed.
