### ISSUE TITLE
Duplicate detector - Detect books with overlapping chapters as duplicates

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#834]
Detect books with overlapping chapters as duplicates even though "ignore chapters" is selected

e.g. `Blah blah gaiden Ch. 1-6`  vs. `Blah blah gaiden Ch. 1-7`

Careful with the alternate spellings
`n-n`
`n - n`
`n,n`
`n , n`

**Comment by Padpoy** [comment]
i too really want this features

**Comment by RobbWatershed** [comment]
Available in v1.17.5
