### ISSUE TITLE
[Just for fun] Achievements

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#838]
Implement achievements into the app, such as (_examples subject to discussion_) :
- **There can be only one** : Set up the app to show only one source
- **Nope.** : Browse to a book whose tags are all blocked
- **The plot thickens** : Read 1000 pages or more
- **Hoarder** : Collect at least 5000 books
- **FBI, open up!** : Collect at least 20 books tagged with illegal tags
- **The Stanley Parable** : Collect at least 20 books tagged with `netorare`
- **Legal Department** : Read the "Licenses" screen from top to bottom
- **Touched Grass** : Don't open hentoid for at least 72 hours
...

More ideas will be suggested in a dedicated Community event (NNN-related acheivement?)

Achievements should have a share function that generates a little "achievement unlocked" image for that achievement.

**Comment by Thewisem** [comment]
Why? Just why are you doing this? Why is this a thing?

**Comment by RobbWatershed** [comment]
That's written on the title. Just. For. Fun.
Plus the Discord community actually voted for this 😁

**Comment by Thewisem** [comment]
Uh uh uh, when your session turns into a game with achievements including the lart with the FBI. I do not want to know who wanted to put the fbi tags. And get an achievement with that. I mean these achievements, your gonna turn hentai into an achievement system. I don't know whether to call you all madlads or hentai masters

**Comment by avluis** [comment]
These should have some weight behind it 🤣 
Integrate these with the Google Play Games SDK for a permanent stain 😸

**Comment by Thewisem** [comment]
Cmon dude, that is sick. Even this is not as wicked as that. Do you want their girlfriends/parents to find out? Its like asking to get caught as well as google knowing how depraved of a person you are. Nononononononono
That is messed up and you sir should not do that please.
