### ISSUE TITLE
Completed/not completed filter ignored by continuous reading

### ISSUE THREAD

**Issue by zLc362** [avluis/Hentoid#839]
**Hentoid Version**:1.15.4

**Device/Android Version**:

**Issue details / Repro steps**:If you have continuous reading on, and filter by completed/not completed the next book ignores the filter

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Fixed by c33114355585bde231754567eeedc504167f9e69
