### ISSUE TITLE
Feature Request: Be able to specify the duration you need to hold down a long press to start quick download

### ISSUE THREAD

**Issue by sushilicious** [avluis/Hentoid#852]
Thanks for the excellent app.

Feature request: The long press to quick download feature is great. However, I find myself often downloading things I don't mean to because it only takes 500ms to register a long press. So, sometimes, even when I'm just scrolling down, hentoid will start downloading a doujin because I had my thumb on it for too long. It would be nice if there was a way to change this threshold.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Included in today's v1.15.13-RC1 (Discord release)
