### ISSUE TITLE
PIN-protection bypass vulnerability

### ISSUE THREAD

**Issue by KseandI** [avluis/Hentoid#876]
## PIN-protection bypass vulnerability

I found a vulnerability with which you can log into hentoid, protected by a password with the "lock when restored from background" parameter. If you quickly switch between applications, you will not need to enter a PIN code, provided that it has already been entered in this session.

This is (probably) not a problem with the "delay" parameter, because it works when it is set to "no delay".

This is my first issue, so I might not have included something important. Ask anything.

**Hentoid Version**: 1.15.14 (453)

**Device/Android Version**: MI MAX 2, Android 10 (custom ROM)

**Issue details / Repro steps**:
1) Open PIN-protected Hentoid.
2) **Enter PIN** (Important, not working on first start).
3) Exit and enter into app.
4) Quickly exit the app and return back.
5) Hentoid unlocked without password.

Note: I found it and recorded it on a hendroid, hentoid fork, but it works on hentoid too.

https://user-images.githubusercontent.com/38111072/144653383-16b1d4c7-476b-4cce-9c1c-18865f47063d.mp4

**Comment by RobbWatershed** [comment]
The PIN is supposed to prevent other people from accessing Hentoid while you lend them your phone.

In the case you're describing, only yourself can trigger that bug, as it needs a quick switch between apps. The PIN is not useful in that case.

**Comment by KseandI** [comment]
Yes, if you give the phone away, before closing the application process, the bug will not work.
But if, after entering the pincode, you give the phone away without closing the application, but simply exiting it, the bug can still be used.  In this case, the "lock when restored from background" parameter is useless.

**Comment by TrainDoctor** [comment]
This is absolutely not a wontfix scenario and absolutely should be addressed. End users use software differently. not every use case needs to be catered to but the possibility of this is quite high.

**Comment by RobbWatershed** [comment]
**My apologies**. I did not reproduce it properly the first time.

Putting it on top of the list.

**Comment by RobbWatershed** [comment]
Fixed for next release
