### ISSUE TITLE
Quick download doesn't work

### ISSUE THREAD

**Issue by iftybito67** [avluis/Hentoid#881]
**Hentoid Version**: 1.15.14

**Device/Android Version**: 10 QKQ1.200830.002

**Issue details / Repro steps**: Websites take a long time to load even though my internet connection is good. also, the quick download doesn't work. after pressing it for a few seconds, nothing happens.

**Stack trace / LogCat**: no error massage that i can find
```ruby
paste stack trace and/or log here
```

https://streamable.com/w6rq1s

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Quick download taking a long time is intimately linked to your loading times being long.

About that, I'm unable to diagnose what happens between Hentoid and nhentai servers. Could be anything, from your home network to a cable under the sea or an army of horny people fapping while being bored on holidays. Try and switch another network, or another location using a VPN.
