### ISSUE TITLE
Opening Hitomi completely freeze the app

### ISSUE THREAD

**Issue by Imnoobatgithub** [avluis/Hentoid#885]
After update 1.15.16 opening Hitomi make the app unresponsive. 

**Hentoid Version**: 1.15.16

**Device/Android Version**:Asus M2 2gb ram

**Issue details / Repro steps**: It open hitomi normally for few second and then the app becomes unresponsive after that.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by Imnoobatgithub** [comment]
Nevermind, changing custom DNS from cloudflare to Quad9 fix the problem.

**Comment by Imnoobatgithub** [comment]
Changing custom DNS to Quad9 fix the app freeze, but load only the first page.

**Comment by RobbWatershed** [comment]
Fixed in today's v1.15.17
