### ISSUE TITLE
Add rating system individually for (books - Artist - Groups)

### ISSUE THREAD

**Issue by Padpoy** [avluis/Hentoid#892]
Add rating system individually for (books - Artist - Groups) 
consist of 5 star from half star to 5 star and adding rating to the sort menu 
if i'am in "by artist" it will sort depending on the artist rating 
if i'am in "all books" it will sort depending on the books rating
and so on

**Comment by Padpoy** [comment]
i suddenly can't enter the discord server it say cant accept invitation

**Comment by RobbWatershed** [comment]
We're already planning to extend the favourite system in #524. What you describe seems to be redundant.

**Comment by RobbWatershed** [comment]
The Discord liks seems to be valid, and the server still runs. Are you sure you followed https://discord.com/invite/QEZ3qk9 ?
