### ISSUE TITLE
No Japanese titles

### ISSUE THREAD

**Issue by Yuushikida** [avluis/Hentoid#912]
So, basically, when downloading a manga, the titles is in romaji instead of Hiragana/Kanji, is there anyway to have it back?

Also, when I try to change that manually, the app crashes

**Comment by RobbWatershed** [comment]
So, basically, when downloading a manga, the titles is in romaji instead of Hiragana/Kanji, is there anyway to have it back?

See #601.

Also, when I try to change that manually, the app crashes

That will be fixed in next release. Thanks for your feedback
