### ISSUE TITLE
Add a behavior when the application does not start because WebView is missing.

### ISSUE THREAD

**Issue by jojoto** [avluis/Hentoid#934]
As the application relies mainly on the "WebView", if the WebView has a problem, or is simply missing (ROM problem or other), Hentoid crashes and launches the "Splash" activity in a loop.

Would it be possible to make sure that after a certain number of errors, the application will stop with a notification explaining that there is a defect with the WebView?

**Hentoid Version**: 1.15.21

**Device/Android Version**: Oukitel K6000 Pro ViperOS 3.1.1 (Android 7.1.2) Unofficial

**Issue details / Repro steps**: Have a bad rom with no Aosp WebView in /system/app/webview and uninstall the Google WebView XD

**Comment by RobbWatershed** [comment]
Roger. Good one
