### ISSUE TITLE
8muses certain comics unavailable

### ISSUE THREAD

**Issue by mate-rix** [avluis/Hentoid#937]
- The current 8muses site used on Hentoid (ie: https://comics.8muses.com/comics)
has few comics removed(i.e : CrazyDad comics)
- If you could add a different 8muses site in the next update instead (Eg: https://8muses.io/), it would be great.

**Comment by RobbWatershed** [comment]
New sources are voted on Discord and planned for the next major versions. I'm noting that one on the voting list, but we can't ignore the votes and add it first. It will be submitted to voting next time those are held.

**Comment by mate-rix** [comment]
> New sources are voted on Discord and planned for the next major versions. I'm noting that one on the voting list, but we can't ignore the votes and add it first. It will be submitted to voting next time those are held.

I'm a noobie on discord so could you let me know when the next voting would be held

**Comment by RobbWatershed** [comment]
I'm receiving one "special site request to consider" every week, so nope. That would invalidate the whole point of voting.

Just log in our Discord server and you'll receive notifications for every release and important event (e.g. votes). I won't push notifications elsewhere.

**Comment by RobbWatershed** [comment]
After discussing it with the team, adding an alternate site as a new source just because some content has been removed from the main site is not strong enough a case. The removed content can be found on other sources (e.g. Porncomix, ExHentai, Luscious)
