### ISSUE TITLE
'This content cannot be downloaded. Sorry' message everytime a doujinshi page is opened on nhentai

### ISSUE THREAD

**Issue by DRWAUN** [avluis/Hentoid#955]
**Hentoid Version**: 
At least since 1.15.21 (including .23)

**Device/Android Version**: Nokia 7 Plus, Android 10, also reproduced it on MuMuPlayer with emulator version 2.3.18

**Issue details / Repro steps**:

_Description_
 As the title says, every time I open a page of doujinshi for the first time on nhentai, I get a the message 'This content cannot be downloaded. Sorry', even though I'm not trying to download anything. This has been happening for the past 3 or so updates? Tried on E-hentai and Tsumino, but it didn't happen there.

_Steps to reproduce:_

1.  Open Hentoid
2. Open nhentai on it
3. Open any doujinshi
4. Click on the thumbnail or any random page to start reading

- Seen: 'This content cannot be downloaded. Sorry' message
- Expected: not this message when opening a new page and not trying to download anything 
5. Go back to the doujinshi overview
6. Open any random page of said doujinshi

- Seen: same message again

This'll happen every time you go from the doujinshi overview to reading any page.

**Stack trace / LogCat**:
Not sure if I found all possible logs, but the logs I did find in .Hentoid were not updated with new errors when I reproduced the message.

![image](https://user-images.githubusercontent.com/101024515/156903611-cb4c8f21-9374-41f5-bfd2-0b113cee5246.png)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Thanks for your feedback. That message isn't intended for the viewer pages, but only for the gallery page when the site has an issue.

We'll find a way to remove it.

**Comment by RobbWatershed** [comment]
Implemented in today's v1.16.1
