### ISSUE TITLE
some problems i have

### ISSUE THREAD

**Issue by qvimxyz** [avluis/Hentoid#968]
**Hentoid Version**: v1.16.1 (513)

**Device/Android Version**: Redmi note 11 / android 11 / MIUI 13

**Issue details / Repro steps**: _asmhentai, hentaifox, imhentai._ I can access the site and click on the comics, but when I open the viewer I can't turn the page, even by clicking on the image or the arrows. all other sites work normally.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Hi and thanks for your feedback.

Do these sites work properly when you open them using the Chrome browser app ?

**Comment by qvimxyz** [comment]
> Hi and thanks for your feedback.
> 
> Do these sites work properly when you open them using the Chrome browser app ?

yes

**Comment by qvimxyz** [comment]
@RobbWatershed  https://streamable.com/xojpqg

**Comment by RobbWatershed** [comment]
Can you try disabling "augmented browser" in the browser preferences ?

**Comment by qvimxyz** [comment]
doesn't work either.

**Comment by RobbWatershed** [comment]
Thanks. Looks like these rascals made it impossible to browse their site if Google Analytics is disabled :-(

I'll make it so the non-augmented browser doesn't block domains anymore, to get the most vanilla experience possible.

**Comment by RobbWatershed** [comment]
Done for next release
