### ISSUE TITLE
Weird Toasts appearing in reader

### ISSUE THREAD

**Issue by AlarmingLength** [avluis/Hentoid#995]
I have been using the app for a while, but this time, when reading, a bunch of strange and alarming toast notifications appeared. I had no way to make sure that these toasts we're coming from the app so I downloaded Toast Source from the play store which allows you to monitor and save a history of toasts. I also downloaded a fork, Hendroid. Hendroid had the same problem and I was able to capture it. Even though it's a different app and maintainer, the messages from Hendroid are the same ones I received on Hentoid. Thanks.

![Screenshot_20220709-195055__01](https://user-images.githubusercontent.com/109009993/178129868-a6149906-9b85-40bd-8e0c-48b1693a99ec.jpg)

**Comment by RobbWatershed** [comment]
As the old saying goes, "it's not a bug, it's a feature"

That's nothing to be worried about. See #754
